dict = {
"AB" : "a",
"A COSTÚDMÁRU" : ["acotumé", "acotume"],
"A DỌNC" : "adonc",
"HÁBYO" : "ai",
"ÁNTS" : ["ainz", "aints"],
"ÁYT" : "ait",
# " " : "al",
"ALÁTS" : ["alez", "alets"],
"AMĘN" : "amen",
"AMĘT" : [["amoit"], 'verbe_imparfait'],
"AMỌNT" : "amont",
"ANGẸLLU" : "angel",
"APPĘLLARUNT" : [["apelleront"], 'verbe_parfait'],
"A PǪRTAT" : [["aporta"], 'verbe_parfait'],
"APPRĘSSU" : ["après", "apres"],
"A RE TENÚTS" : [["aretenuz", "aretenuts"], 'verbe_parfait'],
# " " : "as",
"ALTRE" : "auter",
"ALTRE" : "autre",
"ALTRES" : "autres",
# " " : "ave",
"APĘC" : "avec",
"A VÍSU" : "avis",
"ABĘT" : [["avoit"], 'verbe_imparfait'],
"AWWST" : [["aüst", "aust"], 'verbe_parfait'],
"BELLU" : "bel",
"BENẸDITA" : "beneoite",
"BENẸDITS" : ["beneoiz", "beneoits"],
"BENẸDIRE" : ["beneïr", "beneir"],
"BENẸDICT" : [["beneït", "beneit"], 'verbe_parfait'],
"BĘNE" : "bien",
"BONA" : "bone",
# " " : "cel",
"CESTU" : "cest",
# " " : "cesui",
"CANTÁRE" : "chanter",
"CASCÚN" : "chascun",
"CASCÚNA" : "chascune",
"CASCÚNUS" : "chascuns",
"CARA" : "cher",
# " " : "ci",
# " " : "cil",
"CÍSTU" : "cist",
"COMẸNTYAVĪ" : ["comencié", "comencie"],
"COMPÁNYA" : "compaigni",
"COMPÁNYỌNS" : "compaignons",
# " " : "contrit",
"CỌRSO" : "cor",
"COSTÚDME" : "costume",
"CREÁTTǪRE" : "creator",
"CRISTO" : "crist",
"CǪRE" : "cuer",
# " " : "d",
"DỌMNA" : "dame",
# " " : "davant",
"DE" : "de",
"DĘU" : "deo",
"DESÍDRUNT" : [["desiront"], 'verbe_parfait'],
"DĘU" : "deu",
"DEVÁNT" : "devant",
"DE VERSU" : "dever",
"DEVỌTTAMẸNTE" : "devotement",
"DIE" : "di",
"DÍRA" : [["dira"], 'verbe_futur'],
"DÍRÁ" : [["dirai"], 'verbe_futur'],
"DIXÍT" : [["disit"], 'verbe_parfait'],
"DIXĘT" : [["disoit"], 'verbe_imparfait'],
"DIT" : [["dit"], 'verbe_parfait'],
"DITTAS" : "dites",
"DEBĘT" : [["doit"], 'verbe_present'],
"DOMẸNTRAS" : "domentres",
# " " : "dominus",
"DỌNT" : "dont",
"DORMÍRE" : "dormir",
"DORMĘT" : [["dormoit"], 'verbe_imparfait'],
"DỌLCA" : "douce",
"DỌLCAMẸNTE" : "doucement",
# " " : "el",
# " " : "elle",
"EN" : "en",
"ENDǪRMÍS" : "endormis",
"ẸN OÁTS" : ["enoez", "enoets"],
"ENTẸNDĘT" : [["entendoit"], 'verbe_imparfait'],
"ẸN TEGRÍNAMẸNTE" : "enterinement",
"ẸN TEGRÍNAS" : "enterines",
"ẸNTỌR" : "entor",
"ẸNTRA" : "entre",
"ERUNT" : [["eront"], 'verbe_imparfait'],
"ERIT" : [["ert"], 'verbe_imparfait'],
"ES" : "es",
"ESFǪRTYAT" : [["esforça", "esforca", "esforsa"], 'verbe_parfait'],
"ES GARDAT" : ["esgardé", "esgarde"],
"EST" : [["est"], 'verbe_present'],
"ESTĘT" : [["estoit"], 'verbe_imparfait'],
"ESVẸGLATS" : ["esveillez", "esveillets"],
"ET" : "et",
"OCLOS" : ["euz", "euts"],
"EPẸSCPOS" : "evesques",
"EPẸSCPU" : ["evesquë", "evesque"],
"FÁCRE" : "faire",
"FẸMNAS" : "fames",
"FÍLYU" : "fil",
"FOÍTS" : ["foiz", "foits"],
"FRỌYTS" : ["fruiz", "fruits"],
"FÚT" : [["fu"], 'verbe_parfait'],
"FÚRUNT" : [["furent"], 'verbe_parfait'],
# "GABRÍẸLS" : "gabrieuz",
"GÁRDA" : [["garda"], 'verbe_parfait'],
"GENÍTRÍXA" : ["genitrix", "genitrice"],
"GLORÍỌSSA" : ["glorïouse", "gloriouse"],
"GRATYAS" : "graces",
# "GRATYAS" : "gracias",
# "GRATYA" : "gratia",
# " " : "graüsa", ??
"HABT" : "ha",
"HORAS" : "hores",
"IL" : "il",
"IXÍT" : [["issi"], 'verbe_parfait'],
# "YẸSU" : "jhesu",
"GAUDYǪSAMẸNTE" : "joiosement",
"DYǪRNU" : "jor",
"DYǪRNOS" : "jorz",
# " " : "jusqu",
# " " : "l",
# " " : "la",
"LAÚDAS" : "laudes",
"ILLE" : "le",
"ILLOS" : "les",
"LEVĘTS" : ["levez", "levets"],
# " " : "li",
# " " : "lo",
"LAUDARĘT" : [["loerai"], 'verbe_futur'],
"LAUDAS" : "loes",
"LUÍ" : "lui",
"MERCẸYDE" : "marcis",
"MARÍA" : "maria",
"MARÍA" : "marie",
"MATTÍNAS" : "matines",
"MEYLYỌRA" : "meillura",
"MENERÁ" : [["menrai"], 'verbe_futur'],
"MÁTRE" : "mere",
"MẸSSTĘRU" : "mester",
"MIRÁCCLU" : "miracle",
"MÍSSU" : "mis",
"MẸ" : "moi",
"MỌNYCU" : "moine",
"MỌNYCOS" : "moines",
"MỌNYCU" : "moino",
"MOLTU" : "molt",
"MON" : "mon",
"MOSTĘRYU" : "mostier",
"MỌTTU" : "mot",
"MOLTU" : "mout",
# " " : "n",
# " " : "ne",
"NETA" : "nete",
"NOS" : "nos",
"NOSTRO" : "nostron",
"NǪCTE" : "nuit",
"NỌMME" : "num",
# " " : "o",
"ÁWWUNT" : [["ont"], 'verbe_present'],
"ORGANU" : "orgen",
"ÁWWIT" : [["ot"], 'verbe_parfait'],
"AUDÍ" : [["oï", "oi"], 'verbe_parfait'],
"PAR" : "par",
"PARLÁT" : ["parlé", "parle"],
"PARTÍT" : [["partit"], 'verbe_parfait'],
"PAS" : "pas",
"PLẸNA" : "plena",
"POR" : "por",
"PRECÍỌSSA" : ["precïose", "preciose"],
"PRÍST" : [["prist"], 'verbe_parfait'],
"PROPHĘTTA" : "prophete",
"PǪYS" : "puis",
"PURA" : "pure",
# " " : "q",
"QWÁNTU" : "quant",
"CANTÍQWOS" : "quantiques",
# "CAR" : "quar",
"QWE" : ["que", "quë"],
"QWI" : "qui",
# "QUE" : "quë",
"RE GARDÁRE" : "regarder",
"RE GARDÁ" : ["reguardé", "regarde"],
"REND" : "rent",
"RESPǪNDÍT" : [["respondit"], 'verbe_parfait'],
"REVĘRTÍT" : [["revertit"],'verbe_parfait'],
# " " : "s",
# "" : "saches", #??
"SACRAS" : ["sacrez", "sacres", "sacrets"],
"SÁNCTU" : "saint",
"SÁNCTA" : "sainte",
"SÁNCTOS" : ["sainz", "saints"],
"SALÚTE" : "salu",
"SALÚA" : [["salua"], 'verbe_parfait'],
"SE" : "se",
"SEDĘNT" : "seent",
"SENYǪR" : "seignor",
"SENĘSSTRA" : "senestre",
"SERVÍRE" : "servir",
"SERVÍS" : "servis",
"SES" : "ses",
"SÍDĘT" : [["sidoit"], 'verbe_imparfait'],
"SĘES" : [["soies"], 'verbe_subj'],
"SON" : "son",
"SONATS" : ["sonez", "sonets"],
"SOPLÍĘT" : [["soplioit"], 'verbe_imparfait'],
"SỌBẸNDE" : "sovent",
"TANTỌST" : "tantost",
"TE" : "te",
# " " : "tecum",
"TON" : "ton",
"TORNA" : [["torna"], 'verbe_parfait'],
"TOT" : "tot",
"TOTTUS" : ["toz", "tots"],
"TRES" : "tres",
"TU" : "tu",
"UNU" : "un",
"UNA" : "une",
"VẸGYLÁRE" : "veiller",
"VẸGYLĘT" : [["veilloit"], 'verbe_imparfait'],
"VENÍRE" : "venir",
"VENÍTA" : "venite",
"VENĘT" : [["venoit"], 'verbe_imparfait'],
"VENTRU" : "ventre",
"VENÚ" : "venue",
"VERSU" : "vers",
"VITA" : "vie",
"VĘNIT" : [["vient"], 'verbe_parfait'],
"VIRGA" : ["virge", "virgë"],
# "VIRGA" : "virgë",
"VISU" : [["vis"], 'verbe_parfait'],
"VITU" : [["vit"], 'verbe_parfait'],
"VOCES" : "vois",
"VISUT" : [["voit"], 'verbe_present'],
"VOCES" : ["voiz", "voits"],
"VEDẸRE" : "vooir",
"VOS" : "vos",
"VỌTA" : "vout",
# " " : "zacarie",
}
