dict = {
"AB" : "a",
"A COSTÚDMÁRU" : ["acotumé", "acotume"],
"A DỌNC" : "adonc",
"HÁBYO" : "ai",
"ÁNTS" : ["ainz", "aints"],
"ÁYT" : "ait",
# " " : "al",
"ALÁTS" : ["alez", "alets"],
"AMĘN" : "amen",
"AMĘT" : "amoit",
"AMỌNT" : "amont",
"ANGẸLLU" : "angel",
"APPĘLLARUNT" : "apelleront",
"A PǪRTAT" : "aporta",
"APPRĘSSU" : ["après", "apres"],
"A RE TENÚTS" : ["aretenuz", "aretenuts"],
# " " : "as",
"ALTRE" : "auter",
"ALTRE" : "autre",
"ALTRES" : "autres",
# " " : "ave",
"APĘC" : "avec",
"A VÍSU" : "avis",
"ABĘT" : "avoit",
"AWWST" : ["aüst", "aust"],
"BELLU" : "bel",
"BENẸDITA" : "beneoite",
"BENẸDITS" : ["beneoiz", "beneoits"],
"BENẸDIRE" : ["beneïr", "beneir"],
"BENẸDICT" : ["beneït", "beneit"],
"BĘNE" : "bien",
"BONA" : "bone",
# " " : "cel",
"CESTU" : "cest",
# " " : "cesui",
"CANTÁRE" : "chanter",
"CASCÚN" : "chascun",
"CASCÚNA" : "chascune",
"CASCÚNUS" : "chascuns",
"CARA" : "cher",
# " " : "ci",
# " " : "cil",
"CÍSTU" : "cist",
"COMẸNTYAVĪ" : ["comencié", "comencie"],
"COMPÁNYA" : "compaigni",
"COMPÁNYỌNS" : "compaignons",
# " " : "contrit",
"CỌRSO" : "cor",
"COSTÚDME" : "costume",
"CREÁTTǪRE" : "creator",
"CRISTO" : "crist",
"CǪRE" : "cuer",
# " " : "d",
"DỌMNA" : "dame",
# " " : "davant",
"DE" : "de",
"DĘU" : "deo",
"DESÍDRUNT" : "desiront",
"DĘU" : "deu",
"DEVÁNT" : "devant",
"DE VERSU" : "dever",
"DEVỌTTAMẸNTE" : "devotement",
"DIE" : "di",
"DÍRA" : "dira",
"DÍRÁ" : "dirai",
"DIXÍT" : "disit",
"DIXĘT" : "disoit",
"DIT" : "dit",
"DITTAS" : "dites",
"DEBĘT" : "doit",
"DOMẸNTRAS" : "domentres",
# " " : "dominus",
"DỌNT" : "dont",
"DORMÍRE" : "dormir",
"DORMĘT" : "dormoit",
"DỌLCA" : "douce",
"DỌLCAMẸNTE" : "doucement",
# " " : "el",
# " " : "elle",
"EN" : "en",
"ENDǪRMÍS" : "endormis",
"ẸN OÁTS" : ["enoez", "enoets"],
"ENTẸNDĘT" : "entendoit",
"ẸN TEGRÍNAMẸNTE" : "enterinement",
"ẸN TEGRÍNAS" : "enterines",
"ẸNTỌR" : "entor",
"ẸNTRA" : "entre",
"ERUNT" : "eront",
"ERIT" : "ert",
"ES" : "es",
"ESFǪRTYAT" : ["esforça", "esforca", "esforsa"],
"ES GARDAT" : ["esgardé", "esgarde"],
"EST" : "est",
"ESTĘT" : "estoit",
"ESVẸGLATS" : ["esveillez", "esveillets"],
"ET" : "et",
"OCLOS" : ["euz", "euts"],
"EPẸSCPOS" : "evesques",
"EPẸSCPU" : ["evesquë", "evesque"],
"FÁCRE" : "faire",
"FẸMNAS" : "fames",
"FÍLYU" : "fil",
"FOÍTS" : ["foiz", "foits"],
"FRỌYTS" : ["fruiz", "fruits"],
"FÚT" : "fu",
"FÚRUNT" : "furent",
# "GABRÍẸLS" : "gabrieuz",
"GÁRDA" : "garda",
"GENÍTRÍXA" : ["genitrix", "genitrice"],
"GLORÍỌSSA" : ["glorïouse", "gloriouse"],
"GRATYAS" : "graces",
# "GRATYAS" : "gracias",
# "GRATYA" : "gratia",
# " " : "graüsa", ??
"HABT" : "ha",
"HORAS" : "hores",
"IL" : "il",
"IXÍT" : "issi",
# "YẸSU" : "jhesu",
"GAUDYǪSAMẸNTE" : "joiosement",
"DYǪRNU" : "jor",
"DYǪRNOS" : "jorz",
# " " : "jusqu",
# " " : "l",
# " " : "la",
"LAÚDAS" : "laudes",
"ILLE" : "le",
"ILLOS" : "les",
"LEVĘTS" : ["levez", "levets"],
# " " : "li",
# " " : "lo",
"LAUDARĘT" : "loerai",
"LAUDAS" : "loes",
"LUÍ" : "lui",
"MERCẸYDE" : "marcis",
"MARÍA" : "maria",
"MARÍA" : "marie",
"MATTÍNAS" : "matines",
"MEYLYỌRA" : "meillura",
"MENERÁ" : "menrai",
"MÁTRE" : "mere",
"MẸSSTĘRU" : "mester",
"MIRÁCCLU" : "miracle",
"MÍSSU" : "mis",
"MẸ" : "moi",
"MỌNYCU" : "moine",
"MỌNYCOS" : "moines",
"MỌNYCU" : "moino",
"MOLTU" : "molt",
"MON" : "mon",
"MOSTĘRYU" : "mostier",
"MỌTTU" : "mot",
"MOLTU" : "mout",
# " " : "n",
# " " : "ne",
"NETA" : "nete",
"NOS" : "nos",
"NOSTRO" : "nostron",
"NǪCTE" : "nuit",
"NỌMME" : "num",
# " " : "o",
"ÁWWUNT" : "ont",
"ORGANU" : "orgen",
"ÁWWIT" : "ot",
"AUDÍ" : ["oï", "oi"],
"PAR" : "par",
"PARLÁT" : ["parlé", "parle"],
"PARTÍT" : "partit",
"PAS" : "pas",
"PLẸNA" : "plena",
"POR" : "por",
"PRECÍỌSSA" : ["precïose", "preciose"],
"PRÍST" : "prist",
"PROPHĘTTA" : "prophete",
"PǪYS" : "puis",
"PURA" : "pure",
# " " : "q",
"QWÁNTU" : "quant",
"CANTÍQWOS" : "quantiques",
# "CAR" : "quar",
"QWE" : ["que", "quë"],
"QWI" : "qui",
# "QUE" : "quë",
"RE GARDÁRE" : "regarder",
"RE GARDÁ" : ["reguardé", "regarde"],
"REND" : "rent",
"RESPǪNDÍT" : "respondit",
"REVĘRTÍT" : "revertit",
# " " : "s",
# "" : "saches", #??
"SACRAS" : ["sacrez", "sacres", "sacrets"],
"SÁNCTU" : "saint",
"SÁNCTA" : "sainte",
"SÁNCTOS" : ["sainz", "saints"],
"SALÚTE" : "salu",
"SALÚA" : "salua",
"SE" : "se",
"SEDĘNT" : "seent",
"SENYǪR" : "seignor",
"SENĘSSTRA" : "senestre",
"SERVÍRE" : "servir",
"SERVÍS" : "servis",
"SES" : "ses",
"SÍDĘT" : "sidoit",
"SĘES" : "soies",
"SON" : "son",
"SONATS" : ["sonez", "sonets"],
"SOPLÍĘT" : "soplioit",
"SỌBẸNDE" : "sovent",
"TANTỌST" : "tantost",
"TE" : "te",
# " " : "tecum",
"TON" : "ton",
"TORNA" : "torna",
"TOT" : "tot",
"TOTTUS" : ["toz", "tots"],
"TRES" : "tres",
"TU" : "tu",
"UNU" : "un",
"UNA" : "une",
"VẸGYLÁRE" : "veiller",
"VẸGYLĘT" : "veilloit",
"VENÍRE" : "venir",
"VENÍTA" : "venite",
"VENĘT" : "venoit",
"VENTRU" : "ventre",
"VENÚ" : "venue",
"VERSU" : "vers",
"VITA" : "vie",
"VĘNIT" : "vient",
"VIRGA" : ["virge", "virgë"],
# "VIRGA" : "virgë",
"VISU" : "vis",
"VITU" : "vit",
"VOCES" : "vois",
"VISUT" : "voit",
"VOCES" : ["voiz", "voits"],
"VEDẸRE" : "vooir",
"VOS" : "vos",
"VỌTA" : "vout",
# " " : "zacarie",
}
