print(EvolutionPhonetique.evolution_phonetique("AB")) # a
print(EvolutionPhonetique.evolution_phonetique("A COSTÚDMÁRU")) # acotumé
print(EvolutionPhonetique.evolution_phonetique("A DỌNC")) # adonc
print(EvolutionPhonetique.evolution_phonetique("HÁBYO")) # ai
print(EvolutionPhonetique.evolution_phonetique("ÁNTS")) # ainz
print(EvolutionPhonetique.evolution_phonetique("ÁYT")) # ait
print(EvolutionPhonetique.evolution_phonetique("ALÁTS")) # alez
print(EvolutionPhonetique.evolution_phonetique("AMĘN")) # amen
print(EvolutionPhonetique.evolution_phonetique("AMÁBAT")) # amoit
print(EvolutionPhonetique.evolution_phonetique("AMỌNT")) # amont
print(EvolutionPhonetique.evolution_phonetique("ANGẸLLU")) # angel
print(EvolutionPhonetique.evolution_phonetique("APPĘLLARMUS")) # apelleront
print(EvolutionPhonetique.evolution_phonetique("A PǪRTAT")) # aporta
print(EvolutionPhonetique.evolution_phonetique("APPRĘSSU")) # après
print(EvolutionPhonetique.evolution_phonetique("A RE TENÚTS")) # aretenuz
print(EvolutionPhonetique.evolution_phonetique("ALTRE")) # autre
print(EvolutionPhonetique.evolution_phonetique("ALTRES")) # autres
print(EvolutionPhonetique.evolution_phonetique("APĘC")) # avec
print(EvolutionPhonetique.evolution_phonetique("A VÍSU")) # avis
print(EvolutionPhonetique.evolution_phonetique("ABĘT")) # avoit
print(EvolutionPhonetique.evolution_phonetique("AWWST")) # aüst
print(EvolutionPhonetique.evolution_phonetique("BELLU")) # bel
print(EvolutionPhonetique.evolution_phonetique("BENẸDITA")) # beneoite
print(EvolutionPhonetique.evolution_phonetique("BENẸDITS")) # beneoiz
print(EvolutionPhonetique.evolution_phonetique("BENẸDIRE")) # beneïr
print(EvolutionPhonetique.evolution_phonetique("BENẸDICT")) # beneït
print(EvolutionPhonetique.evolution_phonetique("BĘNE")) # bien
print(EvolutionPhonetique.evolution_phonetique("BONA")) # bone
print(EvolutionPhonetique.evolution_phonetique("CESTU")) # cest
print(EvolutionPhonetique.evolution_phonetique("CANTÁRE")) # chanter
print(EvolutionPhonetique.evolution_phonetique("CASCÚN")) # chascun
print(EvolutionPhonetique.evolution_phonetique("CASCÚNA")) # chascune
print(EvolutionPhonetique.evolution_phonetique("CASCÚNUS")) # chascuns
print(EvolutionPhonetique.evolution_phonetique("CARA")) # cher
print(EvolutionPhonetique.evolution_phonetique("CÍSTU")) # cist
print(EvolutionPhonetique.evolution_phonetique("COMẸNTYAVĪ")) # comencié
print(EvolutionPhonetique.evolution_phonetique("COMPÁNYA")) # compaigni
print(EvolutionPhonetique.evolution_phonetique("COMPÁNYỌNS")) # compaignons
print(EvolutionPhonetique.evolution_phonetique(" ")) # contrit
print(EvolutionPhonetique.evolution_phonetique("CǪRE")) # cuer
print(EvolutionPhonetique.evolution_phonetique("COSTÚDME")) # costume
print(EvolutionPhonetique.evolution_phonetique("CREÁTTǪRE")) # creator
print(EvolutionPhonetique.evolution_phonetique("CRISTO")) # crist
print(EvolutionPhonetique.evolution_phonetique("DỌMNA")) # dame
print(EvolutionPhonetique.evolution_phonetique("DE")) # de
print(EvolutionPhonetique.evolution_phonetique("DĘU")) # deu
print(EvolutionPhonetique.evolution_phonetique("DESÍDRUNT")) # desiront
print(EvolutionPhonetique.evolution_phonetique("DEVÁNT")) # devant
print(EvolutionPhonetique.evolution_phonetique("DE VERSU")) # dever
print(EvolutionPhonetique.evolution_phonetique("DEVỌTTAMẸNTE")) # devotement
print(EvolutionPhonetique.evolution_phonetique("DIE")) # di
print(EvolutionPhonetique.evolution_phonetique("DÍRA")) # dira
print(EvolutionPhonetique.evolution_phonetique("DÍRÁ")) # dirai
print(EvolutionPhonetique.evolution_phonetique("DIXÍT")) # disit
print(EvolutionPhonetique.evolution_phonetique("DIXĘT")) # disoit
print(EvolutionPhonetique.evolution_phonetique("DIT")) # dit
print(EvolutionPhonetique.evolution_phonetique("DITTAS")) # dites
print(EvolutionPhonetique.evolution_phonetique("DEBĘT")) # doit
print(EvolutionPhonetique.evolution_phonetique("DOMẸNTRAS")) # domentres
print(EvolutionPhonetique.evolution_phonetique("DỌNT")) # dont
print(EvolutionPhonetique.evolution_phonetique("DORMÍRE")) # dormir
print(EvolutionPhonetique.evolution_phonetique("DORMĘT")) # dormoit
print(EvolutionPhonetique.evolution_phonetique("DỌLCA")) # douce
print(EvolutionPhonetique.evolution_phonetique("DỌLCAMẸNTE")) # doucement
print(EvolutionPhonetique.evolution_phonetique("EN")) # en
print(EvolutionPhonetique.evolution_phonetique("ENDǪRMÍS")) # endormis
print(EvolutionPhonetique.evolution_phonetique("ẸN OÁTS")) # enoez
print(EvolutionPhonetique.evolution_phonetique("ENTẸNDĘT")) # entendoit
print(EvolutionPhonetique.evolution_phonetique("ẸN TEGRÍNAMẸNTE")) # enterinement
print(EvolutionPhonetique.evolution_phonetique("ẸN TEGRÍNAS")) # enterines
print(EvolutionPhonetique.evolution_phonetique("ẸNTỌR")) # entor
print(EvolutionPhonetique.evolution_phonetique("ẸNTRA")) # entre
print(EvolutionPhonetique.evolution_phonetique("ERUNT")) # eront
print(EvolutionPhonetique.evolution_phonetique("ERIT")) # ert
print(EvolutionPhonetique.evolution_phonetique("ES")) # es
print(EvolutionPhonetique.evolution_phonetique("ESFǪRTYAT")) # esforça
print(EvolutionPhonetique.evolution_phonetique("ES GARDAT")) # esgardé
print(EvolutionPhonetique.evolution_phonetique("EST")) # est
print(EvolutionPhonetique.evolution_phonetique("ESTĘT")) # estoit
print(EvolutionPhonetique.evolution_phonetique("ESVẸGLATS")) # esveillez
print(EvolutionPhonetique.evolution_phonetique("ET")) # et
print(EvolutionPhonetique.evolution_phonetique("ỌCLOS")) # euz
print(EvolutionPhonetique.evolution_phonetique("EPẸSCPOS")) # evesques
print(EvolutionPhonetique.evolution_phonetique("EPẸSCPU")) # evesquë
print(EvolutionPhonetique.evolution_phonetique("FÁCRE")) # faire
print(EvolutionPhonetique.evolution_phonetique("FẸMNAS")) # fames
print(EvolutionPhonetique.evolution_phonetique("FÍLYU")) # fil
print(EvolutionPhonetique.evolution_phonetique("FOÍTS")) # foiz
print(EvolutionPhonetique.evolution_phonetique("FRỌYTS")) # fruiz
print(EvolutionPhonetique.evolution_phonetique("FÚT")) # fu
print(EvolutionPhonetique.evolution_phonetique("FÚRUNT")) # furent
print(EvolutionPhonetique.evolution_phonetique("GÁRDA")) # garda
print(EvolutionPhonetique.evolution_phonetique("GENÍTRÍXA")) # genitrix
print(EvolutionPhonetique.evolution_phonetique("GLORÍỌSSA")) # glorïouse
print(EvolutionPhonetique.evolution_phonetique("GRATYAS")) # gracias
print(EvolutionPhonetique.evolution_phonetique("GRATYA")) # gratia
print(EvolutionPhonetique.evolution_phonetique("HABET")) # ha
print(EvolutionPhonetique.evolution_phonetique("HORAS")) # hores
# print(EvolutionPhonetique.evolution_phonetique("IL")) # il
print(EvolutionPhonetique.evolution_phonetique("EXÍT")) # issi
print(EvolutionPhonetique.evolution_phonetique("GAUDYǪSAMẸNTE")) # joiosement
print(EvolutionPhonetique.evolution_phonetique("DYǪRNU")) # jor
print(EvolutionPhonetique.evolution_phonetique("DYǪRNOS")) # jorz
print(EvolutionPhonetique.evolution_phonetique("LAÚDAS")) # laudes
print(EvolutionPhonetique.evolution_phonetique("ILLE")) # le
print(EvolutionPhonetique.evolution_phonetique("ILLOS")) # les
print(EvolutionPhonetique.evolution_phonetique("LEVĘTS")) # levez
print(EvolutionPhonetique.evolution_phonetique("LAUDARĘT")) # loerai
print(EvolutionPhonetique.evolution_phonetique("LAUDAS")) # loes
print(EvolutionPhonetique.evolution_phonetique("LUÍ")) # lui
print(EvolutionPhonetique.evolution_phonetique("MERCẸYDE")) # marcis
print(EvolutionPhonetique.evolution_phonetique("MARÍA")) # marie
print(EvolutionPhonetique.evolution_phonetique("MATTÍNAS")) # matines
print(EvolutionPhonetique.evolution_phonetique("MEYLYỌRA")) # meillura
print(EvolutionPhonetique.evolution_phonetique("MENERÁ")) # menrai
print(EvolutionPhonetique.evolution_phonetique("MÁTRE")) # mere
print(EvolutionPhonetique.evolution_phonetique("MẸSSTĘRU")) # mester
print(EvolutionPhonetique.evolution_phonetique("MIRÁCCLU")) # miracle
print(EvolutionPhonetique.evolution_phonetique("MÍSSU")) # mis
print(EvolutionPhonetique.evolution_phonetique("MẸ")) # moi
print(EvolutionPhonetique.evolution_phonetique("MỌNYCU")) # moino
print(EvolutionPhonetique.evolution_phonetique("MỌNYCOS")) # moines
print(EvolutionPhonetique.evolution_phonetique("MOLTU")) # mout
print(EvolutionPhonetique.evolution_phonetique("MON")) # mon
print(EvolutionPhonetique.evolution_phonetique("MOSTĘRYU")) # mostier
print(EvolutionPhonetique.evolution_phonetique("MỌTTU")) # mot
print(EvolutionPhonetique.evolution_phonetique("NETA")) # nete
print(EvolutionPhonetique.evolution_phonetique("NOS")) # nos
print(EvolutionPhonetique.evolution_phonetique("NOSTRO")) # nostron
print(EvolutionPhonetique.evolution_phonetique("NǪCTE")) # nuit
print(EvolutionPhonetique.evolution_phonetique("NỌMME")) # num
print(EvolutionPhonetique.evolution_phonetique("ÁWWUNT")) # ont
print(EvolutionPhonetique.evolution_phonetique("ORGANU")) # orgen
print(EvolutionPhonetique.evolution_phonetique("ÁWWIT")) # ot
print(EvolutionPhonetique.evolution_phonetique("AUDÍ")) # oï
print(EvolutionPhonetique.evolution_phonetique("PAR")) # par
print(EvolutionPhonetique.evolution_phonetique("PARLAT")) # parlé
print(EvolutionPhonetique.evolution_phonetique("PARTÍT")) # partit
print(EvolutionPhonetique.evolution_phonetique("PAS")) # pas
print(EvolutionPhonetique.evolution_phonetique("PLẸNA")) # plena
print(EvolutionPhonetique.evolution_phonetique("POR")) # por
print(EvolutionPhonetique.evolution_phonetique("PRECÍỌSSA")) # precïose
print(EvolutionPhonetique.evolution_phonetique("PRÍST")) # prist
print(EvolutionPhonetique.evolution_phonetique("PROPHĘTTA")) # prophete
print(EvolutionPhonetique.evolution_phonetique("PǪYS")) # puis
print(EvolutionPhonetique.evolution_phonetique("PURA")) # pure
print(EvolutionPhonetique.evolution_phonetique("QWÁNTU")) # quant
print(EvolutionPhonetique.evolution_phonetique("CANTÍQWOS")) # quantiques
print(EvolutionPhonetique.evolution_phonetique("CAR")) # quar
print(EvolutionPhonetique.evolution_phonetique("QUE")) # quë
print(EvolutionPhonetique.evolution_phonetique("QUI")) # qui
print(EvolutionPhonetique.evolution_phonetique("RE GARDÁ")) # reguardé
print(EvolutionPhonetique.evolution_phonetique("REND")) # rent
print(EvolutionPhonetique.evolution_phonetique("RESPǪNDÍT")) # respondit
print(EvolutionPhonetique.evolution_phonetique("REVĘRTÍT")) # revertit
print(EvolutionPhonetique.evolution_phonetique("SACRAS")) # sacrez
print(EvolutionPhonetique.evolution_phonetique("SÁNCTU")) # saint
print(EvolutionPhonetique.evolution_phonetique("SÁNCTA")) # sainte
print(EvolutionPhonetique.evolution_phonetique("SÁNCTOS")) # sainz
print(EvolutionPhonetique.evolution_phonetique("SALÚTE")) # salu
print(EvolutionPhonetique.evolution_phonetique("SALÚA")) # salua
print(EvolutionPhonetique.evolution_phonetique("SE")) # se
print(EvolutionPhonetique.evolution_phonetique("SEDĘNT")) # seent
print(EvolutionPhonetique.evolution_phonetique("SENYǪR")) # seignor
print(EvolutionPhonetique.evolution_phonetique("SENĘSSTRA")) # senestre
print(EvolutionPhonetique.evolution_phonetique("SERVÍRE")) # servir
print(EvolutionPhonetique.evolution_phonetique("SERVÍS")) # servis
print(EvolutionPhonetique.evolution_phonetique("SES")) # ses
print(EvolutionPhonetique.evolution_phonetique("SÍDĘT")) # sidoit
print(EvolutionPhonetique.evolution_phonetique("SĘES")) # soies
print(EvolutionPhonetique.evolution_phonetique("SON")) # son
print(EvolutionPhonetique.evolution_phonetique("SONATS")) # sonez
print(EvolutionPhonetique.evolution_phonetique("SOPLÍĘT")) # soplioit
print(EvolutionPhonetique.evolution_phonetique("SỌBẸNDE")) # sovent
print(EvolutionPhonetique.evolution_phonetique("TANTỌST")) # tantost
print(EvolutionPhonetique.evolution_phonetique("TE")) # te
print(EvolutionPhonetique.evolution_phonetique("TON")) # ton
print(EvolutionPhonetique.evolution_phonetique("TORNA")) # torna
print(EvolutionPhonetique.evolution_phonetique("TOT")) # tot
print(EvolutionPhonetique.evolution_phonetique("TOTTUS")) # toz
print(EvolutionPhonetique.evolution_phonetique("TRES")) # tres
print(EvolutionPhonetique.evolution_phonetique("TU")) # tu
print(EvolutionPhonetique.evolution_phonetique("UNU")) # un
print(EvolutionPhonetique.evolution_phonetique("UNA")) # une
print(EvolutionPhonetique.evolution_phonetique("VẸGYLÁRE")) # veiller
print(EvolutionPhonetique.evolution_phonetique("VẸGYLĘT")) # veilloit
print(EvolutionPhonetique.evolution_phonetique("VENÍRE")) # venir
print(EvolutionPhonetique.evolution_phonetique("VENÍTA")) # venite
print(EvolutionPhonetique.evolution_phonetique("VENĘT")) # venoit
print(EvolutionPhonetique.evolution_phonetique("VENTRU")) # ventre
print(EvolutionPhonetique.evolution_phonetique("VENÚ")) # venue
print(EvolutionPhonetique.evolution_phonetique("VERSU")) # vers
print(EvolutionPhonetique.evolution_phonetique("VITA")) # vie
print(EvolutionPhonetique.evolution_phonetique("VĘNIT")) # vient
print(EvolutionPhonetique.evolution_phonetique("VIRGA")) # virgë
print(EvolutionPhonetique.evolution_phonetique("VĘSU")) # vois
print(EvolutionPhonetique.evolution_phonetique("VITU")) # vit
print(EvolutionPhonetique.evolution_phonetique("VĘSUT")) # voit
print(EvolutionPhonetique.evolution_phonetique("VOCES")) # voiz
print(EvolutionPhonetique.evolution_phonetique("VEDẸRE")) # vooir
print(EvolutionPhonetique.evolution_phonetique("VOS")) # vos
print(EvolutionPhonetique.evolution_phonetique("VỌTA")) # vout
