dict = {
"CẸSTĪ" : "cist",
"LES" : "les",
"A" : "a",
"ALO" : "al",
"ADMÁSSU" : "amasse",
"AMĘN" : "amen",
"APPÁCYÁRE" : "apaisier",
"APPẸNSÁRE" : "apenser",
"APPĘLLÁTS" : ["appellez", "appellets"],
"APPRĘSSU" : "apres",
"ARCA" : "arche",
"ARRĘDRAS" : "arrieres",
# "AILLES" : "as",
"ALCÚNA" : "aucune",
"ALMỌNAS" : "aumones",
"ALTRA" : "autre",
"AVÁRÍTYA" : "avarice",
"ABÍT" : [["avit"], 'verbe_parfait'],
"ABĘT" : [["avoi"], 'verbe_imparfait'],
"ABẸRE" : "avoir",
"ABĘT" : [["avoit"], 'verbe_imparfait'],
# " " : "aü",
"BELLU" : "bel",
"BĘNE" : "bien",
# "BONÍ FACĘS" : "bonifaces",
"BRÁCYOS" : ["braz", "brats"],
"BRISÁTA" : ["briseë", "brisee"],
"BRISÁ" : ["brisë", "brise"],
# " " : "c",
"QWASSA" : "casse",
"CE" : "ce",
"CENTU" : "cen",
"CESTU" : "cest",
"CAPĘLLÁNU" : "chapellain",
"CAPĘLLÁNOS" : ["chastainz", "chastaints"],
"CABÁLLU" : "chaval",
"CAUSA" : "chose",
" " : "ci",
"CÍLLE" : "cil",
"QWỌMMO" : "com",
"COMẸNTYA" : "comence",
"COMẸNTYAT" : [["comença", "comensa", "comenca"], 'verbe_parfait'],
"CONTẸNDRE" : "contendre",
"CORRỌTS" : ["corroz", "corrots"],
"COSTÚDMARYUS" : "costumers",
"CRÍ" : "cri",
"CRITÁRE" : "crier",
"CǪYTA" : [["cuida", 'verbe_parfait'],
"CǪYTÁ" : "cuide",
# " " : "cë",
# " " : "d",
"DE" : "de",
"DE FORIS" : "defors",
"DEILLE" : "del",
"DENÁRYUS" : "deners",
"DES PARTÍT" : [["desparti"], 'verbe_parfait'],
"DIGNÍTA" : ["dignité", "dignite"],
"DEBTU" : "doint",
"DONNÁST" : [["donast"], 'verbe_parfait'],
"DONNÁRE" : "doner",
"DỌNT" : "dont",
"DOS" : "dos",
"DỌLCAMẸNTE" : "doucement",
"DWǪDCE" : ["doze", "dotse"],
"DRAPUS" : "dras",
"DURAMẸNTE" : "durement",
"DURÁRE" : "durer",
"DE" : ["dë", "de"],
"DIÁLỌGGUU" : "dialoge",
# " " : "e",
"ECCLĘYSA" : ["eglise", "eglisë"],
# "ECCLĘYSA" : "eglisë",
# " " : "el",
"ẸN" : "en",
"ENFẸRMÁTS" : ["enfermez", "enfermets"],
"ENTRAT" : "entra",
"ERAT" : "ere",
"ERUNT" : [["eront"], 'verbe_present'],
"SCRÍPTU" : "escrit",
"SMARADOS" : ["esmerez", "esmerets"],
"ESPĘRDÚTS" : ["esperduz", "esperduts"],
"EST" : "est",
"ESTÁNT" : "estant",
"EXTĘNDÚAS" : "estendues",
"STĘS" : [["estoies"], 'verbe_imparfait'],
"STÁ" : ["esté", "este"],
"EPẸSCPU" : ["esvesque", "esvesquë"],
# "EPẸSCPU" : "esvesquë",
"ET" : "et",
# "EPẸSCPU" : "evesque",
"EPẸSCPUS" : "evesques",
"EPẸSCPU" : ["evesquë", "evesque"],
"FÁCEBÁT" : [["faisoit"], 'verbe_imparfait'],
"FENNĪ" : [["feni"], 'verbe_parfait'],
"FENNÍTS" : [["feniz", "fenis", "fenits"], 'verbe_parfait'],
"FERMAMẸNTE" : "fermement",
"FẸCYANT" : [["feïssent", "feissent"], 'verbe_subj_imp'],
"FILYU" : "fil",
"FORS" : "fors",
"FORSẸNNÁRE" : "forsener",
"FORSẸNNATU" : "forsenne",
"FORSẸNNATS" : ["forsennez", "forsennets"],
"FREMĪ" : "fremi",
"FÚ" : "fu",
"YECTÁT" : "gitet",
"GLORÍỌSSA" : ["glorïouse", "gloriouse"],
"GRÁNDU" : "grant",
"GREGGǪRYUS" : "gregoires",
"GRÁTU" : ["gré", "gre"],
"HAT" : "ha",
"ǪMO" : "home",
# " " : "i",
"ICẸSTA" : "iceste",
"ILE" : "il",
"IRA" : "ire",
"IRA" : ["irë", "ire"],
"IXÍ" : [["issi"], 'verbe_parfait'],
# " " : "ja",
# " " : "je",
"DYǪRNU" : "jor",
# " " : "l",
# " " : "la",
"LARGAS" : "larges",
# " " : "le",
# " " : "les",
# " " : "lo",
# " " : "li",
# " " : "lor",
# " " : "ma",
"MÁNUS" : "mains",
"MAGÍS" : "mais",
"MAL TALÁNT" : "maltalant",
# " " : "me",
"MÍSU" : [["mis"], 'verbe_parfait'],
"MISĘRRÍCǪRDA" : "misericorde",
"MISIT" : [["mist"], 'verbe_parfait'],
"MOLTU" : "mol",
"MOLTU" : "molt",
"MON" : "mon",
"MORTU" : "mort",
"MORÚT" : [["morut"], 'verbe_parfait'],
# " " : "n",
# " " : "ne",
"NEPỌ" : "nevou",
"NON" : "non",
"NOS" : "nos",
"NULLA" : "nule",
"NÁTUS" : ["nés", "nes"],
"ỌNCLUS" : "oncles",
"AURU" : "or",
"ORÁTYỌNE" : "oraison",
"ORDẸNÁTU" : ["ordené", "ordene"],
# " " : "orprions",
# "HABEBAS" : "orras", ??
"OWT" : [["ot"], 'verbe_parfait'],
# "AWT" : "ou",
"AUDWĪ" : [["oï", "oi"], 'verbe_parfait'],
"PAR" : "par",
"PARLÁVĪ" : [["parla"], 'verbe_parfait'],
"PARAULA" : "parolle",
"PARTÍT" : [["parti"], 'verbe_parfait'],
"PECÚNA" : "pecune",
"PENSÁRE" : "penser",
"PER" : "per",
"PERDÚ" : "perdu",
"PERÍCLU" : "peril",
"PERSǪNNA" : "personne",
"PẸYYTÁTE" : ["pitié", "pitie"],
"POTWĪ" : "po",
"POR" : "por",
"POSÁTS" : ["posez", "posets"],
"PAUPRE" : "povre",
"PAUPRES" : "povres",
"POTÚSTĪ" : [["poüst", "poust"], 'verbe_parfait'],
"PREYÁNT" : "preiant",
"PREYẸSA" : [["preieise"], 'verbe_imparfait'],
"PRESTRES" : "prestres",
"PRIMÁTS" : ["primaz", "primats"], #??
"PRISA" : "prise",
"PRÍST" : [["prist"], 'verbe_parfait'],
"PRỌDỌMNO" : "proudon",
"PǪYSSU" : "puisse",
# " " : "qu",
"QWANDO" : "quant",
"QWAR" : "quar",
"QWE" : "que",
"QWERẸAS" : [["queroies"], 'verbe_imparfait'],
"QWERUNT" : [["queront"], 'verbe_parfait'],
"QWI" : "qui",
"QWE" : ["quë", "que"],
"RECĘWU" : [["receü", "receu"], 'verbe_parfait'],
"RE CỌNTAT" : [["reconte"], 'verbe_present'],
"RENDRE" : "rendre",
"RENDT" : [["rent"], 'verbe_present'],
"RE PRẸNDRE" : "reprendre",
"RESPẸNDÁNTS" : ["respendanz", "respendants"],
"REVENÚTS" : ["revenuz", "revenuts"], #??
# " " : "s",
"SÁNCTU" : "saint",
"SÁNCTUS" : ["sainz", "saints"],
"SE" : "se",
"SEQWES" : "segus",
"SẸNU" : "sein",
"SENES" : ["senz", "sents"],
"SERÁY" : "seraille",
"SERĘT" : [["seroit"], 'verbe_cond'],
"SERVẸBAT" : [["servoit"], 'verbe_imparfait'],
"SES" : "ses",
"SÁPT" : "set",  #??
"SEPELÍTS" : ["seveliz", "sevelits"],
"SÍ" : "si",
"SOAS" : "soies", #??
"SON" : "son",
"SORA POYYA" : [["sorepoia"], 'verbe_parfait'], #??
"SỌBTUS" : ["souz", "souts"],
"SỌBVẸNIT" : [["sovint"], 'verbe_parfait'],
"SỌBTUS" : ["soz", "sots"],
# " " : "t",
"TANTỌST" : "tantost",
"TERRA" : "terre",
"TẸ" : "toi",
"TỌTTS" : ["toz", "tots"],
"TRAYYTO" : "traite",
"TROPÁT" : [["trova"], 'verbe_parfait'],
"TROPÁTS" : ["trovez", "trovets"],
"TROPMUS" : [["trovons"], 'verbe_present'],
"TROPÁTU" : ["trové", "trove"],
"TU" : "tu",
"TỌTTU" : "tuit",
"UNU" : "un",
"UNUS" : "uns",
"VAD" : "va",
"VENDÚTU" : "vendu",
"VENÚTS" : ["venuz", "venuts"],
"VERÍTA" : ["verité", "verite"],
"VẸNWRUNT" : [["vindrent"], 'verbe_parfait'],
"VẸNĪ" : [["vint"], 'verbe_parfait'],
"VIRGA" : "virge",
"VIVUNT" : [["vivent"], 'verbe_present'],
"VOLĘNTYÁRUS" : "volentiers",
# " " : "ça",
}
