dict = {
"CẸSTĪ" : "cist",
"LES" : "les",
"A" : "a",
"ALO" : "al",
"ADMÁSSU" : "amasse",
"AMĘN" : "amen",
"APPÁCYÁRE" : "apaisier",
"APPẸNSÁRE" : "apenser",
"APPĘLLÁTS" : ["appellez", "appellets"],
"APPRĘSSU" : "apres",
"ARCA" : "arche",
"ARRĘDRAS" : "arrieres",
# "AILLES" : "as",
"ALCÚNA" : "aucune",
"ALMỌNAS" : "aumones",
"ALTRA" : "autre",
"AVÁRÍTYA" : "avarice",
"ABÍT" : "avit",
"ABĘT" : "avoi",
"ABẸRE" : "avoir",
"ABĘT" : "avoit",
# " " : "aü",
"BELLU" : "bel",
"BĘNE" : "bien",
# "BONÍ FACĘS" : "bonifaces",
"BRÁCYOS" : ["braz", "brats"],
"BRISÁTA" : ["briseë", "brisee"],
"BRISÁ" : ["brisë", "brise"],
# " " : "c",
"QWASSA" : "casse",
"CE" : "ce",
"CENTU" : "cen",
"CESTU" : "cest",
"CAPĘLLÁNU" : "chapellain",
"CAPĘLLÁNOS" : ["chastainz", "chastaints"],
"CABÁLLU" : "chaval",
"CAUSA" : "chose",
" " : "ci",
"CÍLLE" : "cil",
"QWỌMMO" : "com",
"COMẸNTYA" : "comence",
"COMẸNTYAT" : ["comença", "comensa", "comenca"],
"CONTẸNDRE" : "contendre",
"CORRỌTS" : ["corroz", "corrots"],
"COSTÚDMARYUS" : "costumers",
"CRÍ" : "cri",
"CRITÁRE" : "crier",
"CǪYTA" : "cuida",
"CǪYTÁ" : "cuide",
# " " : "cë",
# " " : "d",
"DE" : "de",
"DE FORIS" : "defors",
"DEILLE" : "del",
"DENÁRYUS" : "deners",
"DES PARTÍT" : "desparti",
"DIGNÍTA" : ["dignité", "dignite"],
"DEBTU" : "doint",
"DONNÁST" : "donast",
"DONNÁRE" : "doner",
"DỌNT" : "dont",
"DOS" : "dos",
"DỌLCAMẸNTE" : "doucement",
"DWǪDCE" : ["doze", "dotse"],
"DRAPUS" : "dras",
"DURAMẸNTE" : "durement",
"DURÁRE" : "durer",
"DE" : ["dë", "de"],
"DIÁLỌGGUU" : "dialoge",
# " " : "e",
"ECCLĘYSA" : ["eglise", "eglisë"],
# "ECCLĘYSA" : "eglisë",
# " " : "el",
"ẸN" : "en",
"ENFẸRMÁTS" : ["enfermez", "enfermets"],
"ENTRAT" : "entra",
"ERAT" : "ere",
"ERUNT" : "eront",
"SCRÍPTU" : "escrit",
"SMARADOS" : ["esmerez", "esmerets"],
"ESPĘRDÚTS" : ["esperduz", "esperduts"],
"EST" : "est",
"ESTÁNT" : "estant",
"EXTĘNDÚAS" : "estendues",
"STĘS" : "estoies",
"STÁ" : ["esté", "este"],
"EPẸSCPU" : ["esvesque", "esvesquë"],
# "EPẸSCPU" : "esvesquë",
"ET" : "et",
# "EPẸSCPU" : "evesque",
"EPẸSCPUS" : "evesques",
"EPẸSCPU" : ["evesquë", "evesque"],
"FÁCEBÁT" : "faisoit",
"FENNĪ" : "feni",
"FENNÍTS" : ["feniz", "fenis", "fenits"],
"FERMAMẸNTE" : "fermement",
"FẸCYANT" : ["feïssent", "feissent"],
"FILYU" : "fil",
"FORS" : "fors",
"FORSẸNNÁRE" : "forsener",
"FORSẸNNATU" : "forsenne",
"FORSẸNNATS" : ["forsennez", "forsennets"],
"FREMĪ" : "fremi",
"FÚ" : "fu",
"YECTÁT" : "gitet",
"GLORÍỌSSA" : ["glorïouse", "gloriouse"],
"GRÁNDU" : "grant",
"GREGGǪRYUS" : "gregoires",
"GRÁTU" : ["gré", "gre"],
"HAT" : "ha",
"ǪMO" : "home",
# " " : "i",
"ICẸSTA" : "iceste",
"ILE" : "il",
"IRA" : "ire",
"IRA" : ["irë", "ire"],
"IXÍ" : "issi",
# " " : "ja",
# " " : "je",
"DYǪRNU" : "jor",
# " " : "l",
# " " : "la",
"LARGAS" : "larges",
# " " : "le",
# " " : "les",
# " " : "lo",
# " " : "li",
# " " : "lor",
# " " : "ma",
"MÁNUS" : "mains",
"MAGÍS" : "mais",
"MAL TALÁNT" : "maltalant",
# " " : "me",
"MÍSU" : "mis",
"MISĘRRÍCǪRDA" : "misericorde",
"MISIT" : "mist",
"MOLTU" : "mol",
"MOLTU" : "molt",
"MON" : "mon",
"MORTU" : "mort",
"MORÚT" : "morut",
# " " : "n",
# " " : "ne",
"NEPỌ" : "nevou",
"NON" : "non",
"NOS" : "nos",
"NULLA" : "nule",
"NÁTUS" : ["nés", "nes"],
"ỌNCLUS" : "oncles",
"AURU" : "or",
"ORÁTYỌNE" : "oraison",
"ORDẸNÁTU" : ["ordené", "ordene"],
# " " : "orprions",
# "HABEBAS" : "orras", ??
"OWT" : "ot",
# "AWT" : "ou",
"AUDWĪ" : ["oï", "oi"],
"PAR" : "par",
"PARLÁVĪ" : "parla",
"PARAULA" : "parolle",
"PARTÍT" : "parti",
"PECÚNA" : "pecune",
"PENSÁRE" : "penser",
"PER" : "per",
"PERDÚ" : "perdu",
"PERÍCLU" : "peril",
"PERSǪNNA" : "personne",
"PẸYYTÁTE" : ["pitié", "pitie"],
"POTWĪ" : "po",
"POR" : "por",
"POSÁTS" : ["posez", "posets"],
"PAUPRE" : "povre",
"PAUPRES" : "povres",
"POTÚSTĪ" : ["poüst", "poust"],
"PREYÁNT" : "preiant",
"PREYẸSA" : "preieise",
"PRESTRES" : "prestres",
"PRIMÁTS" : ["primaz", "primats"], #??
"PRISA" : "prise",
"PRÍST" : "prist",
"PRỌDỌMNO" : "proudon",
"PǪYSSU" : "puisse",
# " " : "qu",
"QWANDO" : "quant",
"QWAR" : "quar",
"QWE" : "que",
"QWERẸAS" : "queroies",
"QWERUNT" : "queront",
"QWI" : "qui",
"QWE" : ["quë", "que"],
"RECĘWU" : ["receü", "receu"],
"RE CỌNTAT" : "reconte",
"RENDRE" : "rendre",
"RENDT" : "rent",
"RE PRẸNDRE" : "reprendre",
"RESPẸNDÁNTS" : ["respendanz", "respendants"],
"REVENÚTS" : ["revenuz", "revenuts"], #??
# " " : "s",
"SÁNCTU" : "saint",
"SÁNCTUS" : ["sainz", "saints"],
"SE" : "se",
"SEQWES" : "segus",
"SẸNU" : "sein",
"SENES" : ["senz", "sents"],
"SERÁY" : "seraille",
"SERĘT" : "seroit",
"SERVẸBAT" : "servoit",
"SES" : "ses",
"SÁPT" : "set",  #??
"SEPELÍTS" : ["seveliz", "sevelits"],
"SÍ" : "si",
"SOAS" : "soies", #??
"SON" : "son",
"SORA POYYA" : "sorepoia", #??
"SỌBTUS" : ["souz", "souts"],
"SỌBVẸNIT" : "sovint",
"SỌBTUS" : ["soz", "sots"],
# " " : "t",
"TANTỌST" : "tantost",
"TERRA" : "terre",
"TẸ" : "toi",
"TỌTTS" : ["toz", "tots"],
"TRAYYTO" : "traite",
"TROPÁT" : "trova",
"TROPÁTS" : ["trovez", "trovets"],
"TROPMUS" : "trovons",
"TROPÁTU" : ["trové", "trove"],
"TU" : "tu",
"TỌTTU" : "tuit",
"UNU" : "un",
"UNUS" : "uns",
"VAD" : "va",
"VENDÚTU" : "vendu",
"VENÚTS" : ["venuz", "venuts"],
"VERÍTA" : ["verité", "verite"],
"VẸNWRUNT" : "vindrent",
"VẸNĪ" : "vint",
"VIRGA" : "virge",
"VIVUNT" : "vivent",
"VOLĘNTYÁRUS" : "volentiers",
# " " : "ça",
}
