print(EvolutionPhonetique.evolution_phonetique("CẸSTĪ")) # cist
print(EvolutionPhonetique.evolution_phonetique("LES")) # les
print(EvolutionPhonetique.evolution_phonetique("A")) # a
print(EvolutionPhonetique.evolution_phonetique("AL")) # al
print(EvolutionPhonetique.evolution_phonetique("ADMÁSSU")) # amasse
print(EvolutionPhonetique.evolution_phonetique("AMĘN")) # amen
print(EvolutionPhonetique.evolution_phonetique("APPÁCYÁRE")) # apaisier
print(EvolutionPhonetique.evolution_phonetique("APPẸNSÁRE")) # apenser
print(EvolutionPhonetique.evolution_phonetique("APPĘLLÁTS")) # appellez
print(EvolutionPhonetique.evolution_phonetique("APPRĘSSU")) # apres
print(EvolutionPhonetique.evolution_phonetique("ARCA")) # arche
print(EvolutionPhonetique.evolution_phonetique("ARRĘDRAS")) # arrieres
print(EvolutionPhonetique.evolution_phonetique("ALCÚNA")) # aucune
print(EvolutionPhonetique.evolution_phonetique("ALMỌNAS")) # aumones
print(EvolutionPhonetique.evolution_phonetique("ALTRA")) # autre
print(EvolutionPhonetique.evolution_phonetique("AVÁRÍTYA")) # avarice
print(EvolutionPhonetique.evolution_phonetique("ABÍT")) # avit
print(EvolutionPhonetique.evolution_phonetique("ABĘT")) # avoi
print(EvolutionPhonetique.evolution_phonetique("ABẸRE")) # avoir
print(EvolutionPhonetique.evolution_phonetique("ABĘT")) # avoit
print(EvolutionPhonetique.evolution_phonetique("BELLU")) # bel
print(EvolutionPhonetique.evolution_phonetique("BĘNE")) # bien
print(EvolutionPhonetique.evolution_phonetique("BRÁCYOS")) # braz
print(EvolutionPhonetique.evolution_phonetique("BRISÁTA")) # briseë
print(EvolutionPhonetique.evolution_phonetique("BRISÁ")) # brisë
print(EvolutionPhonetique.evolution_phonetique("QWASSA")) # casse
print(EvolutionPhonetique.evolution_phonetique("CE")) # ce
print(EvolutionPhonetique.evolution_phonetique("CENTU")) # cen
print(EvolutionPhonetique.evolution_phonetique("CESTU")) # cest
print(EvolutionPhonetique.evolution_phonetique("CAPĘLLÁNU")) # chapellain
print(EvolutionPhonetique.evolution_phonetique("CAPĘLLÁNOS")) # chastainz
print(EvolutionPhonetique.evolution_phonetique("CABÁLLU")) # chaval
print(EvolutionPhonetique.evolution_phonetique("CAUSA")) # chose
print(EvolutionPhonetique.evolution_phonetique(" ")) # ci
print(EvolutionPhonetique.evolution_phonetique("CÍLLE")) # cil
print(EvolutionPhonetique.evolution_phonetique("QWỌMMO")) # com
print(EvolutionPhonetique.evolution_phonetique("COMẸNTYA")) # comence
print(EvolutionPhonetique.evolution_phonetique("COMẸNTYAT")) # comença
print(EvolutionPhonetique.evolution_phonetique("CONTẸNDRE")) # contendre
print(EvolutionPhonetique.evolution_phonetique("CORRỌTUS")) # corroz
print(EvolutionPhonetique.evolution_phonetique("COSTÚDMARYUS")) # costumers
print(EvolutionPhonetique.evolution_phonetique("CRÍ")) # cri
print(EvolutionPhonetique.evolution_phonetique("CRITÁRE")) # crier
print(EvolutionPhonetique.evolution_phonetique("CǪYTA")) # cuida
print(EvolutionPhonetique.evolution_phonetique("CǪYTÁ")) # cuide
print(EvolutionPhonetique.evolution_phonetique("DE")) # dë
print(EvolutionPhonetique.evolution_phonetique("DE FORIS")) # defors
print(EvolutionPhonetique.evolution_phonetique("DEILLE")) # del
print(EvolutionPhonetique.evolution_phonetique("DENÁRYUS")) # deners
print(EvolutionPhonetique.evolution_phonetique("DES PARTÍT")) # desparti
print(EvolutionPhonetique.evolution_phonetique("DIGNÍTA")) # dignité
print(EvolutionPhonetique.evolution_phonetique("DEBTU")) # doint
print(EvolutionPhonetique.evolution_phonetique("DONNÁST")) # donast
print(EvolutionPhonetique.evolution_phonetique("DONNÁRE")) # doner
print(EvolutionPhonetique.evolution_phonetique("DỌNT")) # dont
print(EvolutionPhonetique.evolution_phonetique("DOS")) # dos
print(EvolutionPhonetique.evolution_phonetique("DỌLCAMẸNTE")) # doucement
print(EvolutionPhonetique.evolution_phonetique("DWǪDCE")) # doze
print(EvolutionPhonetique.evolution_phonetique("DRAPUS")) # dras
print(EvolutionPhonetique.evolution_phonetique("DURAMẸNTE")) # durement
print(EvolutionPhonetique.evolution_phonetique("DURÁRE")) # durer
print(EvolutionPhonetique.evolution_phonetique("DIÁLỌGGUU")) # dialoge
print(EvolutionPhonetique.evolution_phonetique("ECCLĘYSA")) # eglisë
print(EvolutionPhonetique.evolution_phonetique("ẸN")) # en
print(EvolutionPhonetique.evolution_phonetique("ENFẸRMÁTS")) # enfermez
print(EvolutionPhonetique.evolution_phonetique("ENTRAT")) # entra
print(EvolutionPhonetique.evolution_phonetique("STÁ")) # esté
print(EvolutionPhonetique.evolution_phonetique("ERUNT")) # eront
print(EvolutionPhonetique.evolution_phonetique("SCRÍPTU")) # escrit
print(EvolutionPhonetique.evolution_phonetique("SMARADOS")) # esmerez
print(EvolutionPhonetique.evolution_phonetique("ESPĘRDÚTS")) # esperduz
print(EvolutionPhonetique.evolution_phonetique("EST")) # est
print(EvolutionPhonetique.evolution_phonetique("ESTÁNT")) # estant
print(EvolutionPhonetique.evolution_phonetique("EXTĘNDÚAS")) # estendues
print(EvolutionPhonetique.evolution_phonetique("STĘS")) # estoies
print(EvolutionPhonetique.evolution_phonetique("EPẸSCPU")) # evesquë
print(EvolutionPhonetique.evolution_phonetique("ET")) # et
print(EvolutionPhonetique.evolution_phonetique("EPẸSCPUS")) # evesques
print(EvolutionPhonetique.evolution_phonetique("FÁCEBÁT")) # faisoit
print(EvolutionPhonetique.evolution_phonetique("FENNĪ")) # feni
print(EvolutionPhonetique.evolution_phonetique("FENNÍTS")) # feniz
print(EvolutionPhonetique.evolution_phonetique("FERMAMẸNTE")) # fermement
print(EvolutionPhonetique.evolution_phonetique("FẸCYANT")) # feïssent
print(EvolutionPhonetique.evolution_phonetique("FILYU")) # fil
print(EvolutionPhonetique.evolution_phonetique("FORS")) # fors
print(EvolutionPhonetique.evolution_phonetique("FORSẸNNÁRE")) # forsener
print(EvolutionPhonetique.evolution_phonetique("FORSẸNNATU")) # forsenne
print(EvolutionPhonetique.evolution_phonetique("FORSẸNNATS")) # forsennez
print(EvolutionPhonetique.evolution_phonetique("FREMĪ")) # fremi
print(EvolutionPhonetique.evolution_phonetique("FÚ")) # fu
print(EvolutionPhonetique.evolution_phonetique("YECTÁT")) # gitet
print(EvolutionPhonetique.evolution_phonetique("GLORÍỌSSA")) # glorïouse
print(EvolutionPhonetique.evolution_phonetique("GRÁNDU")) # grant
print(EvolutionPhonetique.evolution_phonetique("GREGGỌRYUS")) # gregoires
print(EvolutionPhonetique.evolution_phonetique("GRÁTU")) # gré
print(EvolutionPhonetique.evolution_phonetique("HAT")) # ha
print(EvolutionPhonetique.evolution_phonetique("ǪMO")) # home
print(EvolutionPhonetique.evolution_phonetique("ICẸSTA")) # iceste
print(EvolutionPhonetique.evolution_phonetique("ILE")) # il
print(EvolutionPhonetique.evolution_phonetique("IRA")) # irë
print(EvolutionPhonetique.evolution_phonetique("IXÍ")) # issi
print(EvolutionPhonetique.evolution_phonetique("DYǪRNU")) # jor
print(EvolutionPhonetique.evolution_phonetique("LARGAS")) # larges
print(EvolutionPhonetique.evolution_phonetique("MÁNUS")) # mains
print(EvolutionPhonetique.evolution_phonetique("MAGÍS")) # mais
print(EvolutionPhonetique.evolution_phonetique("MAL TALÁNT")) # maltalant
print(EvolutionPhonetique.evolution_phonetique("MÍSU")) # mis
print(EvolutionPhonetique.evolution_phonetique("MISĘRRÍCǪRDA")) # misericorde
print(EvolutionPhonetique.evolution_phonetique("MISIT")) # mist
print(EvolutionPhonetique.evolution_phonetique("MOLTU")) # molt
print(EvolutionPhonetique.evolution_phonetique("MON")) # mon
print(EvolutionPhonetique.evolution_phonetique("MORTU")) # mort
print(EvolutionPhonetique.evolution_phonetique("MORÚT")) # morut
print(EvolutionPhonetique.evolution_phonetique("NEPỌ")) # nevou
print(EvolutionPhonetique.evolution_phonetique("NON")) # non
print(EvolutionPhonetique.evolution_phonetique("NOS")) # nos
print(EvolutionPhonetique.evolution_phonetique("NULLA")) # nule
print(EvolutionPhonetique.evolution_phonetique("NÁTUS")) # nés
print(EvolutionPhonetique.evolution_phonetique("ỌNCLUS")) # oncles
print(EvolutionPhonetique.evolution_phonetique("AURU")) # or
print(EvolutionPhonetique.evolution_phonetique("ORÁTYỌNE")) # oraison
print(EvolutionPhonetique.evolution_phonetique("ORDẸNÁTU")) # ordené
print(EvolutionPhonetique.evolution_phonetique("OWT")) # ot
# print(EvolutionPhonetique.evolution_phonetique("")) # ou
print(EvolutionPhonetique.evolution_phonetique("AUDWĪ")) # oï
print(EvolutionPhonetique.evolution_phonetique("PAR")) # par
print(EvolutionPhonetique.evolution_phonetique("PARLÁVĪ")) # parla
print(EvolutionPhonetique.evolution_phonetique("PARAULA")) # parolle
print(EvolutionPhonetique.evolution_phonetique("PARTÍT")) # parti
print(EvolutionPhonetique.evolution_phonetique("PECÚNA")) # pecune
print(EvolutionPhonetique.evolution_phonetique("PENSÁRE")) # penser
print(EvolutionPhonetique.evolution_phonetique("PER")) # per
print(EvolutionPhonetique.evolution_phonetique("PERDÚ")) # perdu
print(EvolutionPhonetique.evolution_phonetique("PERÍCLU")) # peril
print(EvolutionPhonetique.evolution_phonetique("PERSǪNNA")) # personne
print(EvolutionPhonetique.evolution_phonetique("PẸYYTÁTE")) # pitié
print(EvolutionPhonetique.evolution_phonetique("POTWĪ")) # po
print(EvolutionPhonetique.evolution_phonetique("POR")) # por
print(EvolutionPhonetique.evolution_phonetique("POSÁTS")) # posez
print(EvolutionPhonetique.evolution_phonetique("PAUPRE")) # povre
print(EvolutionPhonetique.evolution_phonetique("PAUPRES")) # povres
print(EvolutionPhonetique.evolution_phonetique("POTÚSTĪ")) # poüst
print(EvolutionPhonetique.evolution_phonetique("PREYÁNT")) # preiant
print(EvolutionPhonetique.evolution_phonetique("PREYẸSA")) # preieise
print(EvolutionPhonetique.evolution_phonetique("PRESTRES")) # prestres
print(EvolutionPhonetique.evolution_phonetique("PRIMÁTS")) # primaz
print(EvolutionPhonetique.evolution_phonetique("PRISA")) # prise
print(EvolutionPhonetique.evolution_phonetique("PRÍST")) # prist
print(EvolutionPhonetique.evolution_phonetique("PRỌDỌMNO")) # proudon
print(EvolutionPhonetique.evolution_phonetique("PǪYSSU")) # puisse
print(EvolutionPhonetique.evolution_phonetique("QWANDO")) # quant
print(EvolutionPhonetique.evolution_phonetique("QWAR")) # quar
print(EvolutionPhonetique.evolution_phonetique("QWE")) # quë
print(EvolutionPhonetique.evolution_phonetique("QWERẸAS")) # queroies
print(EvolutionPhonetique.evolution_phonetique("QWERUNT")) # queront
print(EvolutionPhonetique.evolution_phonetique("QWI")) # qui
print(EvolutionPhonetique.evolution_phonetique("RECĘWU")) # receü
print(EvolutionPhonetique.evolution_phonetique("RE CỌNTAT")) # reconte
print(EvolutionPhonetique.evolution_phonetique("RENDRE")) # rendre
print(EvolutionPhonetique.evolution_phonetique("RENDT")) # rent
print(EvolutionPhonetique.evolution_phonetique("RE PRẸNDRE")) # reprendre
print(EvolutionPhonetique.evolution_phonetique("RESPẸNDÁNTS")) # respendanz
print(EvolutionPhonetique.evolution_phonetique("REVENÚTS")) # revenuz
print(EvolutionPhonetique.evolution_phonetique("SÁNCTU")) # saint
print(EvolutionPhonetique.evolution_phonetique("SÁNCTUS")) # sainz
print(EvolutionPhonetique.evolution_phonetique("SE")) # se
print(EvolutionPhonetique.evolution_phonetique("SEQWES")) # segus
print(EvolutionPhonetique.evolution_phonetique("SẸNU")) # sein
print(EvolutionPhonetique.evolution_phonetique("SENES")) # senz
print(EvolutionPhonetique.evolution_phonetique("SERÁY")) # seraille
print(EvolutionPhonetique.evolution_phonetique("SERĘT")) # seroit
print(EvolutionPhonetique.evolution_phonetique("SERVẸBAT")) # servoit
print(EvolutionPhonetique.evolution_phonetique("SES")) # ses
print(EvolutionPhonetique.evolution_phonetique("SÁPT")) # set
print(EvolutionPhonetique.evolution_phonetique("SEPELÍTS")) # seveliz
print(EvolutionPhonetique.evolution_phonetique("SÍ")) # si
print(EvolutionPhonetique.evolution_phonetique("SOAS")) # soies
print(EvolutionPhonetique.evolution_phonetique("SON")) # son
print(EvolutionPhonetique.evolution_phonetique("SORA POYYA")) # sorepoia
print(EvolutionPhonetique.evolution_phonetique("SỌBTUS")) # soz
print(EvolutionPhonetique.evolution_phonetique("SỌBVẸNIT")) # sovint
print(EvolutionPhonetique.evolution_phonetique("TANTỌST")) # tantost
print(EvolutionPhonetique.evolution_phonetique("TERRA")) # terre
print(EvolutionPhonetique.evolution_phonetique("TẸ")) # toi
print(EvolutionPhonetique.evolution_phonetique("TỌTTS")) # toz
print(EvolutionPhonetique.evolution_phonetique("TRAYYTO")) # traite
print(EvolutionPhonetique.evolution_phonetique("TROPÁT")) # trova
print(EvolutionPhonetique.evolution_phonetique("TROPÁTS")) # trovez
print(EvolutionPhonetique.evolution_phonetique("TROPMUS")) # trovons
print(EvolutionPhonetique.evolution_phonetique("TROPÁTU")) # trové
print(EvolutionPhonetique.evolution_phonetique("TU")) # tu
print(EvolutionPhonetique.evolution_phonetique("TỌTTU")) # tuit
print(EvolutionPhonetique.evolution_phonetique("UNU")) # un
print(EvolutionPhonetique.evolution_phonetique("UNUS")) # uns
print(EvolutionPhonetique.evolution_phonetique("VAD")) # va
print(EvolutionPhonetique.evolution_phonetique("VENDÚTU")) # vendu
print(EvolutionPhonetique.evolution_phonetique("VENÚTS")) # venuz
print(EvolutionPhonetique.evolution_phonetique("VERÍTA")) # verité
print(EvolutionPhonetique.evolution_phonetique("VẸNWRUNT")) # vindrent
print(EvolutionPhonetique.evolution_phonetique("VẸNĪ")) # vint
print(EvolutionPhonetique.evolution_phonetique("VIRGA")) # virge
print(EvolutionPhonetique.evolution_phonetique("VIVUNT")) # vivent
print(EvolutionPhonetique.evolution_phonetique("VOLĘNTYÁRUS")) # volentiers
