dict = {
"AD" : "a",
"ABÁTTES" : "abates", #?? BATTUO
"ABÁTTMUS" : "abaton",
# " " : "abionates ", #NOM PROPRE
"ACỌMPLÍT" : "acomplit",
"ADỌNC" : "adonc",
"AFRÍCA" : "affrica",
"HÁBYO" : "ai",
"HÁBYAS" : "aies",
"ALYT" : "aille",
"HÁBYT" : "ait",
"ADILLE" : "al", #??
"ALÁRE" : "alar",
"ALBAT" : "allet",
"ADILLOS" : "als", #??
"AMĘN" : "amen",
"ADMÍNÍSTRÁBAT" : "aministrave",
"ANNU" : "an",
"ANNOS" : ["anz", "ants"],
"ADỌRABAS" : "aoras", #??
"ADỌRABANT" : "aoravont",
"ADỌRANT" : "aoront",
"APPĘLLAT" : "apelle",
"APPĘLLABAT" : "apelloit",
"APỌSTLU" : "apostre",
"APỌSTLOS" : "apostres",
"ADPRĘSSU" : "apres",
"ARCHẸPẸSCPU" : "archevesque",
"ADLOS" : "as",
"ASCĘNSYO" : "ascension",
"ASÍA" : "asia",
"ALTRA" : "autra",
"ABÁNTE" : "avant",
"ADVĘNĘMĘNTU" : ["avenemenz", "avenements"],
"ADVẸNT" : "avint",
"HABWIT" : "avit",
"HABYÁT" : "avoit",
"HABUNT" : "avont",
"BAPTẸYARE" : "bapteier",
"BENẸ FÍCYỌS" : "beneficios",
# " " : "betsayda ", #NOM PROPRE
"BRISÁTS" : ["brisiez", "brisiets"], #origine du mot très obscure selon le CNRTL
"CELLE" : "cel",
"CELĘBRE" : "celebre",
"CELLA" : "cella",
"CELLOS" : "cels",
"CELLOS" : "ces",
"CESTU" : "cest",
"CESTA" : "cesta",
"CESTOS" : "cestes",
"CESTOS" : "cetes",
"CESTOS" : ["ceux", "ceus"],
"CESTOS" : ["ceuz", "ceuts"],
"CÁPTYÁTS" : ["chacez", "chacets"],
"CAPĘLLÁNUS" : "chapellans",
"CAUSA" : "chosa",
"CAUSAS" : "choses",
"CESTE" : "ci",
"CELLE" : "cil",
"CESTE" : "cist",
"CÍVTA" : "cite",
"CÍVTAS" : ["citez", "citets"],
"CLĘRCS" : ["clerz", "clerts", "clers"],
"CEỌ" : "co",
"COCTỌMẸNTE" : "coitousement", #??
"COLÚMNA" : "columpna",
"COMÁNTYAT" : "comancet",
"COMMÁNDO" : "comando",
"QWỌMDO" : "come",
"COMẸNTYÁRUNT" : "comenceront",
"QUỌMMENTE" : "coment",
"CONSÍLYU" : "conseil",
"CONTÍNUÁMẸNTE" : "continualment",
"CONTÍNUÁMẸNTE" : "continuament",
"CǪRPS" : "cors",
"CONSTRẸNYUNT" : "costreigniont",
"CREDẸRUNT" : "creeront",
"CRẸDUNT" : "creiont",
"CRẸSAT" : "creise",
"CRITÁRE" : "crier",
# " " : "crist ", #Nom propre
"CRỌDÁLS" : "croiels",
"CRỌX" : "crois",
"CRUCÍVYÁẸRUNT" : "crucifieront",
"CǪRS" : "cuers",
"QWI" : "cui",
# "D" : "d ",
"DE" : "de",
"DELLO" : "del",
"DELLOS" : "dels",
"DEMỌRA" : "demora",
"DESĘRTU" : "desert",
"DESǪBTUS" : "desos",
"DEXTRO" : "destro",
"DĘU" : "deu",
"DĘOS" : "deus",
"DEBÚST" : "deust",
"DǪS" : ["deux", "deus"],
"DEVĘRS" : "devers", #à PEU PRèS
"DICT" : "di",
"DYACĘNOS" : "diaquenos",
"DYACĘNOS" : ["diaquenz", "diaquents", "diaquens"],
"DICÍUNT" : "disiont",
"DICÁBAT" : "disoit",
"DICÁVIT" : "dist",
"DICT" : "dit",
"DOCTRÍNA" : "doctrina",
"DǪS" : "does",
"" : "domentres", #Je ne sais pas du tout d'où vient ce mot
"DǪNAT" : "done",
"DONDE" : "dont", #ça va être compliqué
"DǪLCI" : "douci",
"DǪDCE" : "doze",
"DRACỌNOS" : "dracons",
"DRACỌNU" : "dragon",
"DRACỌNOS" : "dragons",
"ETÁTE" : "eago",
"EDÍFYÁRE" : "edifier",
"ECCLĘYSA" : "egleises",
"ECCLĘYSA" : "eglise",
"ẸNLLE" : "el",
"ẸNLLES" : "els",
"ẸN" : "en",
"ẸNFLÁMMAT" : "enflame",
"ẸNFORTYÁRE" : "enforcere",
"ẸNVÍDYỌSUS" : "enious", #Envieux ?
"ẸNSẸGNAT" : "enseigna",
"ẸNSẸGNÍT" : "enseignie",
"ẸNSẸGNÁT" : "enseiguave",
# " " : "epipodio ", #Nom propre
"ERÁT" : "ere",
"ERÁNT" : "eront",
"SPẸRÍTU" : "esperit",
"EST" : "est",
"STÁRE" : "estar",
"EXTẸNGT" : "esteint",
"ESTS" : ["estez", "estets"],
"EXTRÁNUS" : "estranges",
"ET" : "et",
"EVÁNGẸLYO" : "euvangile",
"EPẸSCPU" : "evesquo",
"EPẸSCPOS" : "evesquos",
"FÁCYAS" : "faces",
"FACYẸBANT" : "faisoient",
"FÁYT" : "fait",
"FACYẸRUNT" : "farem",
"FẸDE" : "fei",
# " " : "felipe", #Nom propre
"FẸMNA" : "fenna",
"FERT" : "ferit",
"FẸRMAMẸNTE" : "fermament",
"FERS" : "fers",
"FESTA" : "festa",
"FIGÍCAS" : "fichies",
"FÍLYU" : "fil",
"FÍLYAS" : "filles",
"FÍLYUS" : "fils",
"FACYENT" : "firont",
"FẸCIT" : "fit",
"FORS" : "fors",
"FRÁTER" : "frere",
# " " : "frige ", #Nom propre
"FÚT" : "fu",
"FǪCU" : "fue",
"FÚIS" : "fues",
"FURUNT" : "furent",
"FURUNT" : "furont",
"FUYST" : "fust",
"WADYÁNYAT" : "gaaignet", #Selon le CNRTL, le verbe gagner viendrait du bas francique *waidanjan
# " " : "gai ", #nom propre
# " " : "galeis ", #Nom propre
"GENTS" : ["genz", "gents"],
"GLỌRYA" : "gloiri",
"GLORYǪSA" : "gloriosa",
"GRANDU" : "grant",
"GRANDS" : ["granz", "grants"],
"HABÍTUNT" : "habitont",
"ẸNẸMÍCOS" : "henemies",
"HHERĘSYA" : "heresi",
"ǪMO" : "hom",
"ǪMO" : "homen",
"ǪMOS" : ["homenz", "homents", "homens"],
"HONỌRUS" : "honors",
"HIC" : "i",
"CISTES" : "ices",
"CISTAS" : "icestes",
"IL" : "il",
"ILLIU" : "illi",
"CEIC" : "iqui",
"IRÁTI" : "irie",
"ĘXITSTĪ" : "issi",
# " " : "jaquemo ", #Nom propre
# " " : "jerapolim ", #Nom propre
# " " : "jesu ", #Nom propre
"EGO" : "jo",
"DYỌRNU" : "jor",
"DYỌRNOS" : ["jorz", "jors", "jorts"],
"JÚXTA" : "justa",
"JÚXTA" : "justea",
"ILLA" : "la",
"LAPÍDARUNT" : "lapideront",
"LẸX" : "lei",
# " " : "lengagos", #???
"ILLES" : "les",
"ILLI" : "li",
"LIGÁT" : "lia",
"LIGÁMENS" : "lians",
"ILLO" : "lo",
"ILLǪRU" : "lor",
"ILLOS" : "los",
"LǪCU" : "lue",
"ILLÍ" : "lui",
"LUMẸRYA" : "lumeri",
# " " : "lvii ", #Nombre
# "ME" : "m ",
"MANGPO" : "maint", #Probablement du germain "MANIGIPO"
"MANGPAS" : "maintes",
"MAGÍS" : "mais",
"MALU" : "mal",
"MAL ÁBTU" : "malado",
"MALÍGNA" : "maligna",
"MALS" : "mals",
"MANWÁRYU" : "maneri",
# " " : "maria ", #Nom propre
# " " : "mart ", #Nom propre
# " " : "martis ", #Nom propre
"MÁLUS" : ["mauz", "mauts", "maus"],
"MẸLYOR" : "meiller",
# "MẸ" : "meima ",
"MẸSMO" : "meimo",
"MẸSMO" : "meismo",
"MẸLYÁRYU" : "mellier",
"MEMỌRYA" : "memoiri",
"MENÁVAT" : "menave",
"MENÁTS" : ["menez", "menets"],
"MÁRE" : "mer",
"MEOS" : "mes",
"MẸNSTĘRYO" : "mester",
"MINÍSTRÁBAT" : "ministrave",
"MEUM" : "mon",
"MỌMSẸNYỌR" : "monseignor",
"MONT" : "mont",
"MORTU" : "mort",
"MEUS" : "mos",
"MỌTTU" : "mot",
"MỌLTU" : "mout",
"MỌLTA" : "moutia",
"NÁTUS" : "nas",
"NE" : "ne",
"NEUNU" : "negun",
"NEUNA" : "neguna",
"NI" : "ni",
# "NECUNO" : "no ",
"NOME" : "nom",
"NON" : "non",
"NOS" : "nos",
"NOSTRA" : "nostre",
"NOSTRAS" : "nostres",
"NOSTRO" : "nostron",
"NỌCYÁBLOS" : "nuisables",
"AUCÍDRE" : "ocirre",
"ǪMOS" : ["omenz", "oments", "omens"],
"ONQWAS" : "onques",
"ORDẸNÁRE" : "ordenar",
"ORDẸNÁT" : "ordenet",
"AWWIT" : "ot",
"AUT" : "ou",
"ỌCTRẸA" : "outreie", #???
"PAGANOS" : "paiens",
"PATRE" : "paro",
"PASSÍON" : "passion",
"PECCATǪR" : "pecheors",
"PĘNẸTĘNCYA" : "penetenci",
"PER" : "per",
"PERÍT" : "perie",
"PERSẸQWÍUNT" : "perseguiont",
# " " : "phelipes ", #Nom propre
# " " : "phelipo ", #Nom propre
# " " : "phelipos ", #Nom propre
# " " : "philipo ", #Nom propre
"PLUS" : "plus",
"PǪPLUS" : "pobles",
"PODẸRES" : "poers",
"POTWIT" : "poiet",
"PORTU" : "port",
"POSÁTA" : "posa",
"PRĘDÍCÁVIT" : "predicave",
"PRĘDÍCET" : "prediquet",
"PRẸCÁRYA" : "preieri",
"PRESSU" : "pres",
"PREFÁCTOS" : "preveros", #Je ne suis pas certain de l'étymologie
"PRẸSU" : "pris", #??
"PRẸSUNT" : "pristrent", #??
"PROMẸSSU" : "promeis",
"PROMẸTIT" : "promet",
"PROVÍNCYA" : "provinci",
"PROPǪSTS" : ["provoz", "provots"],
"POSTYUS" : "puis",
"QWANDO" : "quant",
"CAUSA" : ["quauz", "quauts"],
"QWE" : "que",
"QWẸ" : "quei",
"QWI" : "qui",
"QWID" : "quoi",
"RECỌPERANT" : "recovrarem",
"RECỌPÁVERO" : "recovrereis",
"REGYO" : "region",
"REGNU" : "regne",
"REGNU" : "regno",
"REMẸMRYO" : "rehembre",
# " " : "reins ",  #Nom propre
"REDDẸT" : "rendet",
"RESPỌNDIT" : "respondit",
"RESÚSCÍTAT" : "resucitet",
"RESÚRRĘCTO" : "resurreccion",
# "RESÚRRĘXIT" : "resurrexit ",
"REVẸLÁTYO" : "revelacion",
"SACRÍFÍCYO" : "sacrifice",
"SACRÍFÍCYO" : "sacrificio",
"SACRÍFÍCIT" : "sacrifie",
"SALYAS" : "sailles",
"SALWIT" : "saillit",
"SÁNCTO" : "saint",
"SÁNCTOS" : "saintes",
"SÁNCTOS" : ["sainz", "saints"],
"SALVATǪR" : "salveor",
# "SANITA" : "sanita ",
"SALVÁRE" : "saver",
"SAPẸRE" : "savoir",
"SCIẸNTYA" : "scienci",
"SE" : "se",
"SECLO" : "seglo",
"SECLOS" : "seglos",
"SENYǪR" : "seigner",
"SENYǪR" : "seignor",
"SENYǪR" : "seignoro",
" " : "seimet", #???
"SENẸSTRO" : "senestro",
"ERIT" : "sera",
"ERUNT" : "serant",
"SERVIENTE" : "sergant",
"SERVUS" : "sers",
"SUAS" : "ses",
"SEPTE" : "set",
"SEPĘLĘT" : "sevelies",
"SEPĘLÍS" : "sevelis",
"SI" : "si",
"SENYǪR" : "sire",
"SENYǪR" : "sires",
" " : "sit ", #???
"SUBCỌRRT" : "socorru",
"SOFFĘRT" : "sofert",
"SOBFLÁMẸNTE" : "soflament",
"SIT" : "soi",
"SUNT" : "sont",
"ISTOS" : "sos",
"ISTOS" : ["soz", "sots"],
"SUNT" : "sunt",
"ISTOS" : "sus",
"SUSCÍTAVIT" : "suscita",
"TÁCYANT" : "taisesant",
"TALIS" : "tal",
"TANTU" : "tant",
"TANTǪSTU" : "tantost",
"TACÍTA" : "tasia",
"TE" : "te",
"TENĘBROS" : "tenebres",
"TENẸRUNT" : "teniont",
"TERTYU" : ["terz", "terts"],
"TORNÁT" : "tornet",
"TOTTU" : "tot",
"TOTTAS" : ["totez", "totes", "totets"],
"TOTTOS" : ["toz", "tots"],
"TRAMÁS" : "trameis",
"TRAMAVIT" : "tramist", #??
"TRANS PASSAVẸRUNT" : "trapaseront",
"TRANS PASSÁRE" : "trapassar",
"TU" : "tu",
"TUA" : "tua",
"TOTTU" : "tuit",
"UNU" : "um",
"UNA" : "una",
"UNA" : "une",
"UNAS" : "unes",
"UNOS" : "uns",
"VÁDO" : "vai",
"VÁDAM" : "vanes",
"VẸNUNT" : "veient",
"VENÍRIT" : "venira",
"VENÍT" : "venit",
"VERUS" : "verais",
"VIRTÚTES" : "vertus",
"VISUS" : "veus",
"VITA" : "via",
"VENYAT" : "vigne",
"VIGỌRỌSAMẸNTE" : "vigorosement",
# " " : "vii ", #Nombre
"VIRGÍNA" : "virgina",
"VIRGÍNAS" : "virgines",
"VOS" : "vos",
# " " : "xxx ", #nombre
"IDOLA" : "ydola",
"IDOLAS" : "ydoles",
# " " : "yerapolin", #Nom propre
"IMAGẸNA" : "ymagena",
}
