print(EvolutionPhonetique.evolution_phonetique("AD")) # a
print(EvolutionPhonetique.evolution_phonetique("ABBÁTYA")) # abaie
print(EvolutionPhonetique.evolution_phonetique("ADÍDA")) # ahie
print(EvolutionPhonetique.evolution_phonetique("HÁBYA")) # aie
print(EvolutionPhonetique.evolution_phonetique("ADILLE")) # al
print(EvolutionPhonetique.evolution_phonetique("ALÁCROS")) # alegres
print(EvolutionPhonetique.evolution_phonetique("ALLMỌNAS")) # almones
print(EvolutionPhonetique.evolution_phonetique("ADMÁSSAS")) # amassets
print(EvolutionPhonetique.evolution_phonetique("AMĘN")) # amen
print(EvolutionPhonetique.evolution_phonetique("AMÍCU")) # amiu
print(EvolutionPhonetique.evolution_phonetique("AMÍCOS")) # amis
print(EvolutionPhonetique.evolution_phonetique("ADNÚNTYÁTYO")) # anunciacion
print(EvolutionPhonetique.evolution_phonetique("ANOS")) # ans
print(EvolutionPhonetique.evolution_phonetique("ÁLMAS")) # armes
print(EvolutionPhonetique.evolution_phonetique("ADTÁNTU")) # atant
print(EvolutionPhonetique.evolution_phonetique("ALSÍ")) # aussi
print(EvolutionPhonetique.evolution_phonetique("ALTRẸSSÍ")) # autresi
print(EvolutionPhonetique.evolution_phonetique("ADVẸNÍT")) # avenit
print(EvolutionPhonetique.evolution_phonetique("HABẸTS")) # avets
print(EvolutionPhonetique.evolution_phonetique("HABẸANT")) # avoient
print(EvolutionPhonetique.evolution_phonetique("BÁSYANT")) # baisent
print(EvolutionPhonetique.evolution_phonetique("BASSU")) # bas
print(EvolutionPhonetique.evolution_phonetique("BĘNE")) # bien
print(EvolutionPhonetique.evolution_phonetique("BONU")) # bon
print(EvolutionPhonetique.evolution_phonetique("BONTÁ")) # bonte
print(EvolutionPhonetique.evolution_phonetique("CE")) # ce
print(EvolutionPhonetique.evolution_phonetique("CELLA")) # cele
print(EvolutionPhonetique.evolution_phonetique("CELẸBBRAWIT")) # celebroit
print(EvolutionPhonetique.evolution_phonetique("CELĘSTA")) # celeste
print(EvolutionPhonetique.evolution_phonetique("CERTÁNAMẸNTE")) # certainement
print(EvolutionPhonetique.evolution_phonetique("CESTOS")) # ceuts
print(EvolutionPhonetique.evolution_phonetique("CANTẸANT")) # chantoient
print(EvolutionPhonetique.evolution_phonetique("CAPĘLLA")) # chapelle
print(EvolutionPhonetique.evolution_phonetique("CAUSA")) # chose
print(EvolutionPhonetique.evolution_phonetique("CÍLLE")) # cil
print(EvolutionPhonetique.evolution_phonetique("CLĘRCU")) # clerc
print(EvolutionPhonetique.evolution_phonetique("CLÁRA")) # clere
print(EvolutionPhonetique.evolution_phonetique("QWỌMMO")) # com
print(EvolutionPhonetique.evolution_phonetique("COMẸNTYAVĪ")) # comencie
print(EvolutionPhonetique.evolution_phonetique("COMTÁTU")) # conte
print(EvolutionPhonetique.evolution_phonetique("CORA")) # core
print(EvolutionPhonetique.evolution_phonetique("CỌRRT")) # cort
print(EvolutionPhonetique.evolution_phonetique("COSTÚDME")) # cotume
print(EvolutionPhonetique.evolution_phonetique("CRÍSTO")) # crist
print(EvolutionPhonetique.evolution_phonetique("CRÍSTUS")) # crisz
print(EvolutionPhonetique.evolution_phonetique("CỌGYTỌANT")) # cuidoient
print(EvolutionPhonetique.evolution_phonetique("DE")) # de
print(EvolutionPhonetique.evolution_phonetique("DE DẸNTUS")) # dedents
print(EvolutionPhonetique.evolution_phonetique("DELLO")) # del
print(EvolutionPhonetique.evolution_phonetique("DĘU")) # de
print(EvolutionPhonetique.evolution_phonetique("DĘOS")) # deus
print(EvolutionPhonetique.evolution_phonetique("DÍRE")) # dire
print(EvolutionPhonetique.evolution_phonetique("DÍCT")) # dit
print(EvolutionPhonetique.evolution_phonetique("DONAT")) # doné
print(EvolutionPhonetique.evolution_phonetique("DỌLCA")) # douce #Problème de palatalisation
print(EvolutionPhonetique.evolution_phonetique("ÁWWĪ")) # ei
print(EvolutionPhonetique.evolution_phonetique("EN")) # en
print(EvolutionPhonetique.evolution_phonetique("ẸNGLATĘRRA")) # engleterre
print(EvolutionPhonetique.evolution_phonetique("ENSAPẸLLĪ")) # enseveli
print(EvolutionPhonetique.evolution_phonetique("ENTRÁTU")) # entre
print(EvolutionPhonetique.evolution_phonetique("ENVÍRỌNBANT")) # environoient
print(EvolutionPhonetique.evolution_phonetique("ERAT")) # ere
print(EvolutionPhonetique.evolution_phonetique("ERANT")) # eront
print(EvolutionPhonetique.evolution_phonetique("SCǪLTATU")) # escoute
print(EvolutionPhonetique.evolution_phonetique("ESTĘT")) # estoie
print(EvolutionPhonetique.evolution_phonetique("ET")) # et
print(EvolutionPhonetique.evolution_phonetique("EWÚS")) # euts
print(EvolutionPhonetique.evolution_phonetique("FACYA")) # face
print(EvolutionPhonetique.evolution_phonetique("FACTA")) # faite
print(EvolutionPhonetique.evolution_phonetique("FẸNNĪ")) # fenie
print(EvolutionPhonetique.evolution_phonetique("FẸNNÍS")) # fenis
print(EvolutionPhonetique.evolution_phonetique("FESTA")) # fest
print(EvolutionPhonetique.evolution_phonetique("FILYU")) # fil
print(EvolutionPhonetique.evolution_phonetique("FÍRUNT")) # firont
print(EvolutionPhonetique.evolution_phonetique("FONDÁTA")) # fondee
print(EvolutionPhonetique.evolution_phonetique("FORMANT")) # forment
print(EvolutionPhonetique.evolution_phonetique("FORS")) # fors
print(EvolutionPhonetique.evolution_phonetique("FUĪ")) # fu
print(EvolutionPhonetique.evolution_phonetique("FURANT")) # furent
print(EvolutionPhonetique.evolution_phonetique("FUSSANT")) # fussent
print(EvolutionPhonetique.evolution_phonetique("WARDA")) # garde
print(EvolutionPhonetique.evolution_phonetique("GLORÍỌS")) # glorios
print(EvolutionPhonetique.evolution_phonetique("GLORÍOSA")) # gloriose
print(EvolutionPhonetique.evolution_phonetique("GRÁTTYA")) # grace
print(EvolutionPhonetique.evolution_phonetique("GRÁTTYAS")) # graces
print(EvolutionPhonetique.evolution_phonetique("GRANDU")) # grant
print(EvolutionPhonetique.evolution_phonetique("HHALTU")) # haut
print(EvolutionPhonetique.evolution_phonetique("ǪMO")) # hom
print(EvolutionPhonetique.evolution_phonetique("OMĘN")) # homen
print(EvolutionPhonetique.evolution_phonetique("HHONǪR")) # honor
print(EvolutionPhonetique.evolution_phonetique("HHONǪRRANT")) # honoront
print(EvolutionPhonetique.evolution_phonetique("HÍC")) # i
print(EvolutionPhonetique.evolution_phonetique("ILLE")) # il
print(EvolutionPhonetique.evolution_phonetique("ÍNTRỌYTO")) # introite
print(EvolutionPhonetique.evolution_phonetique("ISSÍ")) # iqui
print(EvolutionPhonetique.evolution_phonetique("IRA")) # ire
print(EvolutionPhonetique.evolution_phonetique(" ")) # jhesu
print(EvolutionPhonetique.evolution_phonetique("GAUDYÁNS")) # joiants
print(EvolutionPhonetique.evolution_phonetique("GAUDYA")) # joië
print(EvolutionPhonetique.evolution_phonetique("DYǪRNU")) # jor
print(EvolutionPhonetique.evolution_phonetique("LA")) # la
print(EvolutionPhonetique.evolution_phonetique("LARMAS")) # larmes
print(EvolutionPhonetique.evolution_phonetique("LO")) # lo
print(EvolutionPhonetique.evolution_phonetique("LOS")) # les
print(EvolutionPhonetique.evolution_phonetique("LEVANT")) # levent
print(EvolutionPhonetique.evolution_phonetique("LI")) # li
print(EvolutionPhonetique.evolution_phonetique("LǪCU")) # liu
print(EvolutionPhonetique.evolution_phonetique("LONGU")) # lonc
print(EvolutionPhonetique.evolution_phonetique("LORU")) # lor
print(EvolutionPhonetique.evolution_phonetique("LOROS")) # lors
print(EvolutionPhonetique.evolution_phonetique("MÁNS")) # mains
print(EvolutionPhonetique.evolution_phonetique("MÁNIT")) # maint
print(EvolutionPhonetique.evolution_phonetique("MALU")) # mal
print(EvolutionPhonetique.evolution_phonetique("MERCẸYDE")) # merci
print(EvolutionPhonetique.evolution_phonetique("MARÍA")) # marie
print(EvolutionPhonetique.evolution_phonetique("MERÁBÍLYANT")) # meravillont
print(EvolutionPhonetique.evolution_phonetique("MÁTRA")) # merë
print(EvolutionPhonetique.evolution_phonetique("MẸSSA")) # messe
print(EvolutionPhonetique.evolution_phonetique("METTẸRS")) # meters
print(EvolutionPhonetique.evolution_phonetique("MIRÁCCLU")) # miracle
print(EvolutionPhonetique.evolution_phonetique("MONASTĘRYU")) # monestei
print(EvolutionPhonetique.evolution_phonetique("MOTTĘRU")) # motier
print(EvolutionPhonetique.evolution_phonetique("NOME")) # nom
print(EvolutionPhonetique.evolution_phonetique("NOS")) # nos
print(EvolutionPhonetique.evolution_phonetique("NOVĘLLA")) # novelle
print(EvolutionPhonetique.evolution_phonetique("NOVĘLLAMẸNTE")) # novellemant
print(EvolutionPhonetique.evolution_phonetique("NUUS")) # nus
print(EvolutionPhonetique.evolution_phonetique("AUNT")) # ont
print(EvolutionPhonetique.evolution_phonetique("HAUR")) # or
print(EvolutionPhonetique.evolution_phonetique("ORÁTYỌNES")) # oraisons
print(EvolutionPhonetique.evolution_phonetique("AURUNT")) # orent
print(EvolutionPhonetique.evolution_phonetique("PRẸYMUS")) # prions
print(EvolutionPhonetique.evolution_phonetique("ÁWTU")) # ot
print(EvolutionPhonetique.evolution_phonetique("AUÚT")) # ou
print(EvolutionPhonetique.evolution_phonetique("AUDÍRE")) # oir
print(EvolutionPhonetique.evolution_phonetique("PASSÁTS")) # passez
print(EvolutionPhonetique.evolution_phonetique("PAGẸYSE")) # pais
print(EvolutionPhonetique.evolution_phonetique("PITTÁ")) # pite
print(EvolutionPhonetique.evolution_phonetique("PLORÁNT")) # plorant
print(EvolutionPhonetique.evolution_phonetique("PLORS")) # plors
print(EvolutionPhonetique.evolution_phonetique("PǪPLOS")) # pobles
print(EvolutionPhonetique.evolution_phonetique("POTẸTS")) # poets
print(EvolutionPhonetique.evolution_phonetique("POR")) # por
print(EvolutionPhonetique.evolution_phonetique("POTRÁT")) # porroit
print(EvolutionPhonetique.evolution_phonetique("PRETYǪSU")) # precio
print(EvolutionPhonetique.evolution_phonetique("PRETYǪSA")) # preciose
print(EvolutionPhonetique.evolution_phonetique("PRESSE")) # pres
print(EvolutionPhonetique.evolution_phonetique("PRĘRYA")) # priere
print(EvolutionPhonetique.evolution_phonetique("PRẸSU")) # pris
print(EvolutionPhonetique.evolution_phonetique("QWANDO")) # quant
print(EvolutionPhonetique.evolution_phonetique("QWE")) # quë
print(EvolutionPhonetique.evolution_phonetique("QWI")) # qui
print(EvolutionPhonetique.evolution_phonetique("RELÍGÍO")) # religion
print(EvolutionPhonetique.evolution_phonetique("REMANSÍRUNT")) # remansiront
print(EvolutionPhonetique.evolution_phonetique("RENDUNT")) # rendont
print(EvolutionPhonetique.evolution_phonetique("RESÚRAXĪ")) # resurexi
print(EvolutionPhonetique.evolution_phonetique("SWA")) # sa
print(EvolutionPhonetique.evolution_phonetique("SAYLÍRE")) # saillir
print(EvolutionPhonetique.evolution_phonetique("SÁNCTUS")) # saints
print(EvolutionPhonetique.evolution_phonetique("SÁNCTA")) # sainte
print(EvolutionPhonetique.evolution_phonetique("SINE")) # san
print(EvolutionPhonetique.evolution_phonetique("SANGU")) # sanc
print(EvolutionPhonetique.evolution_phonetique("SAPỌNS")) # savons
print(EvolutionPhonetique.evolution_phonetique("SECCǪRS")) # socors
print(EvolutionPhonetique.evolution_phonetique("SENYǪR")) # seignor
print(EvolutionPhonetique.evolution_phonetique("SENTĪ")) # senti
print(EvolutionPhonetique.evolution_phonetique("SI")) # si
print(EvolutionPhonetique.evolution_phonetique("SỌY")) # soi
print(EvolutionPhonetique.evolution_phonetique("SỌN")) # son
print(EvolutionPhonetique.evolution_phonetique("SOBẸNDE")) # sovent
print(EvolutionPhonetique.evolution_phonetique("SỌBTRÁCTA")) # soztraite
print(EvolutionPhonetique.evolution_phonetique("TÁLI")) # tel
print(EvolutionPhonetique.evolution_phonetique("TENIT")) # tenit
print(EvolutionPhonetique.evolution_phonetique("TENÚ")) # tenu
print(EvolutionPhonetique.evolution_phonetique("TERRA")) # terre
print(EvolutionPhonetique.evolution_phonetique("TOTTUS")) # tots
print(EvolutionPhonetique.evolution_phonetique("TRANSGLÚTTĪ")) # transgluti
print(EvolutionPhonetique.evolution_phonetique("TREMLÁT")) # trembla
print(EvolutionPhonetique.evolution_phonetique("TRETỌTTU")) # tretuit
print(EvolutionPhonetique.evolution_phonetique("TROPÁRUNT")) # troverent
print(EvolutionPhonetique.evolution_phonetique("TROPÁTU")) # trove
print(EvolutionPhonetique.evolution_phonetique("TỌTTU")) # tuit
print(EvolutionPhonetique.evolution_phonetique("UNU")) # un
print(EvolutionPhonetique.evolution_phonetique("UNA")) # une
print(EvolutionPhonetique.evolution_phonetique("UMQWAS")) # unques
print(EvolutionPhonetique.evolution_phonetique("VESTÍMẸNTS")) # vestiments
print(EvolutionPhonetique.evolution_phonetique("VẸDRE")) # veir
print(EvolutionPhonetique.evolution_phonetique("VITA")) # via
print(EvolutionPhonetique.evolution_phonetique("VẸNRUNT")) # vindrent
print(EvolutionPhonetique.evolution_phonetique("VIDRUNT")) # vire
print(EvolutionPhonetique.evolution_phonetique("VIRGA")) # virge
print(EvolutionPhonetique.evolution_phonetique("VOCES")) # voits
print(EvolutionPhonetique.evolution_phonetique("VOOS")) # vos
