dict = {
"AD" : "a",
"HÁBYO" : "ai",
"ADILLE" : "al",
"AMĘN" : "amen",
"APPELLÁTA" : "apellee", #Du coup, un E atone entre deux double P et deux double L reste
"APPRĘSSU" : ["aprés", "apres"],
"ALTRES" : "autres",
"HABẸT" :"aveit",
"HABẸRE" : "avoir",
"HABẸT" : "avoit",
"ADYUTA" : ["aïe", "aie"],
"ADYUT" : ["aït", "ait"],
"BENẸDITA" : ["beneïte", "beneite"],
"BESỌNYA" : "besoign", #Emprunté du francique
"BRAÁNYA" : "brahaigne", #Étymologie obscure
"BRAÁNYA" : ["brahaingnë", "brahaingne"],
"CAUSA" : "causa",
# " " : "ce",
# " " : "cele",
# " " : "celle",
# " " : "cest",
# " " : "ceste",
# " " : "ceuz",
"CAPTÍVA" : "chaitive",
"CAUSA" : "chose",
"QUOMDO" : "come",
"COMMẸNTYA" : ["comença", "comenca"],
"CONCEPÚ" : ["conçut", "concut"],
"CORPUS" : "cors",
"CRITU" : "cri",
# " " : "crist",
"CRUATS" : ["crüez", "cruets"],
"CǪRE" : "cuer",
# " " : "d",
# " " : "de",
# " " : "del",
"DEÚ" : "deu",
"DEÚS" : "deus",
"DIE" : "di",
"DÍRE" : "dire",
"DIXĘT" : "disoit",
"DOLỌR" : "dolor",
"DONATA" : "donee",
"DONDE" : "dont",
"DỌLCA" : "douce",
"DỌTS" : ["douz", "douts"],
"DURAMẸNTE" : "durement",
"ECCLĘYSA" : "eglise",
"AENSIC" : "einsi",
# " " : "el",
# " " : "ele",
# " " : "elle",
# " " : "en",
"ẸNC HORA" : "encor",
"ẸNFÁNS" : "enfant",
"ẸNFÁNS" : "enfes",
"ẸNFÁNTA" : "enffanta",
# " " : "ensens",
"ENTẸNDÚA" : "entendue",
"ENTẸNDÚ" : "entendu",
"ẸNTRA" : "entre",
"ERAT" : "ert",
"ERAT" : "erë",
"ES" : "es",
"ES BAÍA" : "esbahie",
"ESCÚRSÍS" : "escurzis",
"SPẸRÍTU" : "esperit",
"EST" : "est",
"ESTĘT" : "estoit",
"ESTAT" : "esté",
"ET" : "et",
"FẸMNA" : "fame",
"FẸMNA" : "feme",
"FẸNÍTS" : ["feniz", 'fenits'],
"FEBRA" : "fevre",
"FILYU" : "fil",
"FENNA" : "fina",
"FOR SENATA" : "forsennee",
"FORTI" : "fort",
"FRANCYA" : ["francë", "france"],
"FREQWĘNTĘT" : "frequentoit",
"FRUCTU" : "fruit",
"FUI" : "fu",
"FUI" : "fuio",
"FUSTI" : "fust",
"GENTS" : "genz",
# "" : "gins", #??
"GRANDU" : "grant",
"HAT" : "ha",
"UNQWA" : "hanc",
# " " : "i",
# " " : "il",
"IRATA" : "iree",
# " " : "je",
# " " : "jhesu",
"GAWDYA" : "joi",
"GAWDYA" : "joie",
"GAWDYAS" : "jois",
"GAWDYA" : ["joië", "joie"],
"DYǪRNU" : "jor",
# " " : "l",
# " " : "la",
# " " : "le",
# " " : "les",
# " " : "li",
# " " : "lo",
"LAUDUNT" : "loont",
"LORS" : "lor",
"MAGÍS" : "mais",
"MAL ASTRÚMA" : "malastrua",
"MALA" : "male",
"MARÍA" : "marie",
"MẸ" : "mei",
"MERABẸLYA" : "meraville",
"MATRA" : "mere",
"MERÍTA" : "merite",
"MATRA" : ["merë", "mere"],
# " " : "mes",
"MIRÁCLU" : "miracle",
"MISĘRA" : "misere",
"MISĘRRÍCǪRDA" : "misericorde",
"MISĘRRÍCǪRDA" : "misericordi",
"MOLYĘRE" : "moiller",
"MOLTU" : "molt",
# " " : "mon",
"MONASTĘRYU" : "monester",
"MORTU" : "mort",
"MORTUS" : ["morz", "morts"],
"MỌSTĘRYU" : "moster",
"MUTÁT" : "mua",
# " " : "n",
# " " : "ne",
# " " : "non",
# " " : "nos",
"NǪCTE" : "nuit",
"NULU" : "nul",
# " " : "o",
"ÁWWUNT" : "ont",
"ORÁTYONS" : "oraisons",
"ÁWWUT" : "ot",
# " " : "ou",
"AUDÍRUNT" : ["oïront", "oiront"],
"PAVÍMĘNTU" : "paviment",
"PẸNA" : "peina",
# " " : "per",
"PERDTÚ" : "perdu",
"PATRE" : "pere",
"PERFÁCTU" : "perfait",
"PETÍTÍONS" : ["peticïons", "peticions"],
"PLOR" : "plor",
"PLORÁRE" : "plorer",
# " " : "plus",
"PǪPLU" : "pobles",
"POTERAT" : "pooint", #??
# " " : "por",
"PORTA" : ["porté", "porte"],
"POSAT" : "posa",
"PRẸMARYAMẸNTE" : "premeiriment",
# " " : "presses", #??
"PRECÁRE" : "prier",
"PRECARYA" : "priere",
"PRISSU" : "pris",
"PRIST" : "prist",
"PRODǪMO" : "prodome",
# " " : "q",
"QWANTU" : "quant",
"CAR" : "quar",
# " " : "que",
"QWAERRA" : ["querrë", "querre"],
# " " : "qui",
# " " : "quë",
"REGNA" : "regne",
"REVIXIT" : "revisquit",
"REGÍNA" : ["reïne", "reine"],
# " " : "s",
# " " : "sa",
"SÁNCTU" : "saint",
"SÁNCTA" : "sainte",
"SAPẸRE" : "savoir",
"SECLU" : "segle",
"SENTÍT" : "sentit",
# " " : "ses",
"SECCỌTRE" : "socor",
"SUBTÁNE MENTE" : "sodanement",
# " " : "soi",
# " " : "son",
# " " : "sovendement", #Voir Le commentaire de Maffei Boillat
"SUSCÍTA" : "suscité",
"TANTU" : "tant",
"TẸ" : "tei",
# " " : "tel",
"TOSTU" : "tost",
"TOTTA" : "tote",
"TOTTAS" : "totes",
"TOTTUS" : "toz",
"TRISTU" : "tristor",
"TǪTTĪ" : "tuit",
"UNU" : "un",
"UNA" : "une",
"UNU" : "unt",
"VẸGLYA" : "veil",
"VẸGLYA" : "veilla",
"VẸGLYĘT" : "veilloit",
"VẸZES" : "veis",
"VENĘUNT" : "venoient",
"VENĘT" : "venoit",
"VENTRU" : "ventre",
"VEDĘRE" : "veoir",
"VERTAS" : "verais",
"VERCỌNDYA" : "vergoigne",
"VERTA" : ["verté", "verte"],
"VEÚ" : ["veüe", "veue"],
"VENĪ" : "vint",
"VIRGA" : "virge",
"VẸCÍNOS" : "visins",
"VIST" : "vit",
"VĘS" : "vois",
"VOLĘUNT" : "voloient",
"VOLĘNTÁRYU" : "volunter",
"VENUNT" : "vont",
" " : "ço",
}
