print(EvolutionPhonetique.evolution_phonetique("AD")) # a
print(EvolutionPhonetique.evolution_phonetique("HÁBYO")) # ai
print(EvolutionPhonetique.evolution_phonetique("ADILLE")) # al
print(EvolutionPhonetique.evolution_phonetique("AMĘN")) # amen
print(EvolutionPhonetique.evolution_phonetique("APPELLÁTA")) # apellee
print(EvolutionPhonetique.evolution_phonetique("APPRĘSSU")) # aprés
print(EvolutionPhonetique.evolution_phonetique("ALTRES")) # autres
print(EvolutionPhonetique.evolution_phonetique("HABẸT")) # avoit
print(EvolutionPhonetique.evolution_phonetique("HABẸRE")) # avoir
print(EvolutionPhonetique.evolution_phonetique("ADYUTA")) # aïe
print(EvolutionPhonetique.evolution_phonetique("ADYUT")) # aït
print(EvolutionPhonetique.evolution_phonetique("BENẸDITA")) # beneïte
print(EvolutionPhonetique.evolution_phonetique("BESỌNYA")) # besoign
print(EvolutionPhonetique.evolution_phonetique("BRAÁNYA")) # brahaingnë
print(EvolutionPhonetique.evolution_phonetique("CAUSA")) # chose
print(EvolutionPhonetique.evolution_phonetique("CAPTÍVA")) # chaitive
print(EvolutionPhonetique.evolution_phonetique("QUOMDO")) # come
print(EvolutionPhonetique.evolution_phonetique("COMMẸNTYA")) # comença
print(EvolutionPhonetique.evolution_phonetique("CONCEPÚ")) # conçut
print(EvolutionPhonetique.evolution_phonetique("CORPUS")) # cors
print(EvolutionPhonetique.evolution_phonetique("CRITU")) # cri
print(EvolutionPhonetique.evolution_phonetique("CRUATS")) # crüez
print(EvolutionPhonetique.evolution_phonetique("CǪRE")) # cuer
print(EvolutionPhonetique.evolution_phonetique("DEÚ")) # deu
print(EvolutionPhonetique.evolution_phonetique("DEÚS")) # deus
print(EvolutionPhonetique.evolution_phonetique("DIE")) # di
print(EvolutionPhonetique.evolution_phonetique("DÍRE")) # dire
print(EvolutionPhonetique.evolution_phonetique("DIXĘT")) # disoit
print(EvolutionPhonetique.evolution_phonetique("DOLỌR")) # dolor
print(EvolutionPhonetique.evolution_phonetique("DONATA")) # donee
print(EvolutionPhonetique.evolution_phonetique("DONDE")) # dont
print(EvolutionPhonetique.evolution_phonetique("DỌLCA")) # douce
print(EvolutionPhonetique.evolution_phonetique("DỌTS")) # douz
print(EvolutionPhonetique.evolution_phonetique("DURAMẸNTE")) # durement
print(EvolutionPhonetique.evolution_phonetique("ECCLĘYSA")) # eglise
print(EvolutionPhonetique.evolution_phonetique("AENSIC")) # einsi
print(EvolutionPhonetique.evolution_phonetique("ẸNC HORA")) # encor
print(EvolutionPhonetique.evolution_phonetique("ẸNFÁNS")) # enfes
print(EvolutionPhonetique.evolution_phonetique("ẸNFÁNTA")) # enffanta
print(EvolutionPhonetique.evolution_phonetique("ENTẸNDÚA")) # entendue
print(EvolutionPhonetique.evolution_phonetique("ENTẸNDÚ")) # entendu
print(EvolutionPhonetique.evolution_phonetique("ẸNTRA")) # entre
print(EvolutionPhonetique.evolution_phonetique("ERAT")) # erë
print(EvolutionPhonetique.evolution_phonetique("ES")) # es
print(EvolutionPhonetique.evolution_phonetique("ES BAÍA")) # esbahie
print(EvolutionPhonetique.evolution_phonetique("ESCÚRSÍS")) # escurzis
print(EvolutionPhonetique.evolution_phonetique("SPẸRÍTU")) # esperit
print(EvolutionPhonetique.evolution_phonetique("EST")) # est
print(EvolutionPhonetique.evolution_phonetique("ESTĘT")) # estoit
print(EvolutionPhonetique.evolution_phonetique("ESTAT")) # esté
print(EvolutionPhonetique.evolution_phonetique("ET")) # et
print(EvolutionPhonetique.evolution_phonetique("FẸMNA")) # feme
print(EvolutionPhonetique.evolution_phonetique("FẸNÍTS")) # feniz
print(EvolutionPhonetique.evolution_phonetique("FEBRA")) # fevre
print(EvolutionPhonetique.evolution_phonetique("FILYU")) # fil
print(EvolutionPhonetique.evolution_phonetique("FENNA")) # fina
print(EvolutionPhonetique.evolution_phonetique("FOR SENATA")) # forsennee
print(EvolutionPhonetique.evolution_phonetique("FORTI")) # fort
print(EvolutionPhonetique.evolution_phonetique("FRANCYA")) # francë
print(EvolutionPhonetique.evolution_phonetique("FREQWĘNTĘT")) # frequentoit
print(EvolutionPhonetique.evolution_phonetique("FRUCTU")) # fruit
print(EvolutionPhonetique.evolution_phonetique("FUI")) # fuio
print(EvolutionPhonetique.evolution_phonetique("FUSTI")) # fust
print(EvolutionPhonetique.evolution_phonetique("GENTS")) # genz
print(EvolutionPhonetique.evolution_phonetique("GRANDU")) # grant
print(EvolutionPhonetique.evolution_phonetique("HAT")) # ha
print(EvolutionPhonetique.evolution_phonetique("UNQWA")) # hanc
print(EvolutionPhonetique.evolution_phonetique("IRATA")) # iree
print(EvolutionPhonetique.evolution_phonetique("GAWDYA")) # joië
print(EvolutionPhonetique.evolution_phonetique("GAWDYAS")) # jois
print(EvolutionPhonetique.evolution_phonetique("DYǪRNU")) # jor
print(EvolutionPhonetique.evolution_phonetique("LAUDUNT")) # loont
print(EvolutionPhonetique.evolution_phonetique("LORS")) # lor
print(EvolutionPhonetique.evolution_phonetique("MAGÍS")) # mais
print(EvolutionPhonetique.evolution_phonetique("MAL ASTRÚMA")) # malastrua
print(EvolutionPhonetique.evolution_phonetique("MALA")) # male
print(EvolutionPhonetique.evolution_phonetique("MARÍA")) # marie
print(EvolutionPhonetique.evolution_phonetique("MẸ")) # mei
print(EvolutionPhonetique.evolution_phonetique("MERABẸLYA")) # meraville
print(EvolutionPhonetique.evolution_phonetique("MATRA")) # merë
print(EvolutionPhonetique.evolution_phonetique("MERÍTA")) # merite
print(EvolutionPhonetique.evolution_phonetique("MIRÁCLU")) # miracle
print(EvolutionPhonetique.evolution_phonetique("MISĘRA")) # misere
print(EvolutionPhonetique.evolution_phonetique("MISĘRRÍCǪRDA")) # misericordi
print(EvolutionPhonetique.evolution_phonetique("MOLYĘRE")) # moiller
print(EvolutionPhonetique.evolution_phonetique("MOLTU")) # molt
print(EvolutionPhonetique.evolution_phonetique("MONASTĘRYU")) # monester
print(EvolutionPhonetique.evolution_phonetique("MORTU")) # mort
print(EvolutionPhonetique.evolution_phonetique("MORTUS")) # morz
print(EvolutionPhonetique.evolution_phonetique("MỌSTĘRYU")) # moster
print(EvolutionPhonetique.evolution_phonetique("MUTÁT")) # mua
print(EvolutionPhonetique.evolution_phonetique("NǪCTE")) # nuit
print(EvolutionPhonetique.evolution_phonetique("NULU")) # nul
print(EvolutionPhonetique.evolution_phonetique("ÁWWUNT")) # ont
print(EvolutionPhonetique.evolution_phonetique("ORÁTYONS")) # oraisons
print(EvolutionPhonetique.evolution_phonetique("ÁWWUT")) # ot
print(EvolutionPhonetique.evolution_phonetique("AUDÍRUNT")) # oïront
print(EvolutionPhonetique.evolution_phonetique("PAVÍMĘNTU")) # paviment
print(EvolutionPhonetique.evolution_phonetique("PẸNA")) # peina
print(EvolutionPhonetique.evolution_phonetique("PERDTÚ")) # perdu
print(EvolutionPhonetique.evolution_phonetique("PATRE")) # pere
print(EvolutionPhonetique.evolution_phonetique("PERFÁCTU")) # perfait
print(EvolutionPhonetique.evolution_phonetique("PETÍTÍONS")) # peticïons
print(EvolutionPhonetique.evolution_phonetique("PLOR")) # plor
print(EvolutionPhonetique.evolution_phonetique("PLORÁRE")) # plorer
print(EvolutionPhonetique.evolution_phonetique("PǪPLU")) # pobles
print(EvolutionPhonetique.evolution_phonetique("POTERAT")) # pooint
print(EvolutionPhonetique.evolution_phonetique("PORTA")) # porté
print(EvolutionPhonetique.evolution_phonetique("POSAT")) # posa
print(EvolutionPhonetique.evolution_phonetique("PRẸMARYAMẸNTE")) # premeiriment
print(EvolutionPhonetique.evolution_phonetique("PRECÁRE")) # prier
print(EvolutionPhonetique.evolution_phonetique("PRECARYA")) # priere
print(EvolutionPhonetique.evolution_phonetique("PRISSU")) # pris
print(EvolutionPhonetique.evolution_phonetique("PRIST")) # prist
print(EvolutionPhonetique.evolution_phonetique("PRODǪMO")) # prodome
print(EvolutionPhonetique.evolution_phonetique("QWANTU")) # quant
print(EvolutionPhonetique.evolution_phonetique("CAR")) # quar
print(EvolutionPhonetique.evolution_phonetique("QWAERRA")) # querrë
print(EvolutionPhonetique.evolution_phonetique("REGNA")) # regne
print(EvolutionPhonetique.evolution_phonetique("REVIXIT")) # revisquit
print(EvolutionPhonetique.evolution_phonetique("REGÍNA")) # reïne
print(EvolutionPhonetique.evolution_phonetique("SÁNCTU")) # saint
print(EvolutionPhonetique.evolution_phonetique("SÁNCTA")) # sainte
print(EvolutionPhonetique.evolution_phonetique("SAPẸRE")) # savoir
print(EvolutionPhonetique.evolution_phonetique("SECLU")) # segle
print(EvolutionPhonetique.evolution_phonetique("SENTÍT")) # sentit
print(EvolutionPhonetique.evolution_phonetique("SECCỌTRE")) # socor
print(EvolutionPhonetique.evolution_phonetique("SUBTÁNE MENTE")) # sodanement
print(EvolutionPhonetique.evolution_phonetique("SUSCÍTA")) # suscité
print(EvolutionPhonetique.evolution_phonetique("TANTU")) # tant
print(EvolutionPhonetique.evolution_phonetique("TẸ")) # tei
print(EvolutionPhonetique.evolution_phonetique("TOSTU")) # tost
print(EvolutionPhonetique.evolution_phonetique("TOTTA")) # tote
print(EvolutionPhonetique.evolution_phonetique("TOTTAS")) # totes
print(EvolutionPhonetique.evolution_phonetique("TOTTUS")) # toz
print(EvolutionPhonetique.evolution_phonetique("TRISTU")) # tristor
print(EvolutionPhonetique.evolution_phonetique("TǪTTĪ")) # tuit
print(EvolutionPhonetique.evolution_phonetique("UNU")) # unt
print(EvolutionPhonetique.evolution_phonetique("NA")) # une
print(EvolutionPhonetique.evolution_phonetique("VẸGLYA")) # veilla
print(EvolutionPhonetique.evolution_phonetique("VẸGLYĘT")) # veilloit
print(EvolutionPhonetique.evolution_phonetique("VENIS")) # veis
print(EvolutionPhonetique.evolution_phonetique("VENĘUNT")) # venoient
print(EvolutionPhonetique.evolution_phonetique("VENĘT")) # venoit
print(EvolutionPhonetique.evolution_phonetique("VENTRU")) # ventre
print(EvolutionPhonetique.evolution_phonetique("VEDĘRE")) # veoir
print(EvolutionPhonetique.evolution_phonetique("VEDRÁS")) # verais
print(EvolutionPhonetique.evolution_phonetique("VERCỌNDYA")) # vergoigne
print(EvolutionPhonetique.evolution_phonetique("VERTA")) # verté
print(EvolutionPhonetique.evolution_phonetique("VEÚ")) # veüe
print(EvolutionPhonetique.evolution_phonetique("VENIT")) # vint
print(EvolutionPhonetique.evolution_phonetique("VIRGA")) # virge
print(EvolutionPhonetique.evolution_phonetique("VICÍNOS")) # visins
print(EvolutionPhonetique.evolution_phonetique("VIST")) # vit
print(EvolutionPhonetique.evolution_phonetique("VĘS")) # vois
print(EvolutionPhonetique.evolution_phonetique("VOLĘUNT")) # voloient
print(EvolutionPhonetique.evolution_phonetique("VOLĘNTÁRYU")) # volunter
print(EvolutionPhonetique.evolution_phonetique("VENUNT")) # vont
