dict = {
"HAT" : "a",
"ACCAPTĘT" : "achatoit",
# " " : "ai",
# " " : "al",
"AMLĘT" : "alloit",
"AMĘN" : "amen",
"APPRĘSSU" : ["aprés", "apres"],
"ADRĘTYOS" : "arieres",
"ADVERSU" : "avers",
"BONUS" : "bons",
# " " : "cel",
# " " : "cest",
"CAMBYARAS" : "changeres",
"CĘLU" : "ciel",
# " " : "cil",
"COMMANDA" : "comanda",
"COMĘNTYA" : ["comença", 'comenca'],
"CORPUS" : "cors",
"CRESSÍST" : "cressist",
"CRISTU" : "crist",
# " " : "d",
# " " : "de",
# " " : "del",
"DE LEGÁLUS" : ["delëauz", "deleauts"],
# " " : "des",
"DĘU" : "deu",
"DĘOS" : "deus",
"DIT" : "dit",
# " " : "doint", #??
"DOLANTS" : ["dolenz", "dolents"],
"DỌLCA" : "douce",
# " " : "en",
"EN TORNU" : "entor",
"EN VERSU" : "envers",
"ERAT" : "ere",
"ERUNT" : "eront",
"EST" : "est",
"ESTĘT" : "estoit",
# " " : "et",
"FÁCĘT" : "faisoit",
"FÁCTU" : "fait",
# " " : "fauz",
"FẸDE" : "fei",
"FELỌNS" : "fellons",
"FẸNÍT" : "fenit",
"FORS" : "fors",
# " " : "fraudra", #??
"WAÍDAN" : "gaaing", #?
"JẸCTA" : ["gité", "gite"],
"GRAVẸUNT" : "grevoient",
"HAT" : "ha",
"ǪMO" : "hom",
"HONỌRÁRE" : "honorer",
# " " : "i",
# " " : "il",
"EXÍT" : "issi",
"JADÍES" : "jadis",
# " " : "jhesu",
# " " : "jhesus",
"GAUDYA" : "joi",
"JUDCAMẸNTE" : "jugement",
"JURA" : "jura",
"JURÁRE" : "jurer",
"JURẸT" : "juroit",
# " " : "jë",
# " " : "l",
# " " : "la",
"LAYDẸAMẸNTS" : "laideiemenz",
"LAYDẸÁRE" : "laideier",
"LASSATU" : ["laisé", "laise"],
# " " : "le",
"LẸNGWA" : "lengue",
# " " : "les",
"LABRAS" : "levres",
# " " : "li",
# " " : "lo",
# " " : "los",
"MÁNOS" : "mains",
"MAGÍS" : "mais",
"MAMẸLLAS" : "mamelles",
"MERCÁTÁNTS" : "marchaanz",
"MERCÁTU" : ["marchié", "marchie"],
"MERCÁTOS" : ["marchiés", "marchies"],
"MARÍA" : "marie",
"MEMBROS" : "menbres",
"MERÁBÍLYUNT" : "meravilleront",
"MATRA" : "mere",
"MOLTU" : "molt",
# " " : "ne",
"NEGRỌR" : "nezor",
# " " : "nos",
# " " : "on",
# " " : "ont",
"PATÍẸNMẸNTE" : ["pacïenment", "pacienment"],
# " " : "per",
"PIETA" : "pidie",
# " " : "pié",
"PLẸNU" : "plein",
"PLẸNA" : "pleinna",
# " " : "por",
# " " : "qu",
# " " : "que",
# " " : "qui",
"RENAÍAS" : ["reneïes", "reneies"], #??
"REPRǪPYAS" : "reproches",
"REGÍ" : "roi",
# " " : "sa",
"SÁNCTA" : "sainte",
# " " : "se",
"SẸNE" : ["senz", "sents"],
# " " : "ses",
"SEPELÍRE" : "sevelir",
"SỌFFRĘT" : "soffroit",
# " " : "son",
"SỌBẸNDE" : "sovent",
"TANTỌST" : "tantost",
"TENDIT" : "tendit",
"TERRÁUTS" : ["terrauz", "terrauts"],
"TORNARUNT" : "torneront",
"TORQUOT" : "torzot",
"TRABÚCAT" : "trabucha",
"TRACTA" : ["traitë", "traite"],
"TỌTTĪ" : "tuit",
"UNU" : "un",
"UNOS" : "uns",
"VENDĘT" : "vendoit",
"VẸNDCA" : "venga",
"VẸNDCÁNCYA" : "vengance",
"VENÚ" : "venu",
"VEÚ" : ["veü", 'veu'],
"VIRGA" : "virgine",
# " " : "ço",
}
