dict = {
"HAT" : "a",
"ACCAPTĘT" : [["achatoit"], 'verbe_imparfait'],
# " " : "ai",
# " " : "al",
"AMLĘT" : [["alloit"], 'verbe_imparfait'],
"AMĘN" : "amen",
"APPRĘSSU" : ["aprés", "apres"],
"ADRĘTYOS" : "arieres",
"ADVERSU" : "avers",
"BONUS" : "bons",
# " " : "cel",
# " " : "cest",
"CAMBYARAS" : "changeres",
"CĘLU" : "ciel",
# " " : "cil",
"COMMANDA" : [["comanda"], 'verbe_parfait'],
"COMĘNTYA" : [["comença", 'comenca'], 'verbe_parfait'],
"CORPUS" : "cors",
"CRESSÍST" : [["cressist"], 'verbe_parfait'],
"CRISTU" : "crist",
# " " : "d",
# " " : "de",
# " " : "del",
"DE LEGÁLUS" : ["delëauz", "deleauts"],
# " " : "des",
"DĘU" : "deu",
"DĘOS" : "deus",
"DIT" : [["dit"], 'verbe_parfait'],
# " " : "doint", #??
"DOLANTS" : ["dolenz", "dolents"],
"DỌLCA" : "douce",
# " " : "en",
"EN TORNU" : "entor",
"EN VERSU" : "envers",
"ERAT" : [["ere"], 'verbe_imparfait'],
"ERUNT" : [["eront"], 'verbe_imparfait'],
"EST" : [["est"], 'verbe_present'],
"ESTĘT" : [["estoit"], 'verbe_imparfait'],
# " " : "et",
"FÁCĘT" : [["faisoit"], 'verbe_imparfait'],
"FÁCTU" : "fait",
# " " : "fauz",
"FẸDE" : "fei",
"FELỌNS" : "fellons",
"FẸNÍT" : [["fenit"], 'verbe_parfait'],
"FORS" : "fors",
# " " : "fraudra", #??
"WAÍDAN" : "gaaing", #?
"JẸCTA" : ["gité", "gite"],
"GRAVẸUNT" : [["grevoient"], 'verbe_imparfait'],
"HAT" : "ha",
"ǪMO" : "hom",
"HONỌRÁRE" : "honorer",
# " " : "i",
# " " : "il",
"EXÍT" : "issi",
"JADÍES" : "jadis",
# " " : "jhesu",
# " " : "jhesus",
"GAUDYA" : "joi",
"JUDCAMẸNTE" : "jugement",
"JURA" : [["jura"], 'verbe_parfait'],
"JURÁRE" : "jurer",
"JURẸT" : [["juroit"], 'verbe_imparfait'],
# " " : "jë",
# " " : "l",
# " " : "la",
"LAYDẸAMẸNTS" : "laideiemenz",
"LAYDẸÁRE" : "laideier",
"LASSATU" : ["laisé", "laise"],
# " " : "le",
"LẸNGWA" : "lengue",
# " " : "les",
"LABRAS" : "levres",
# " " : "li",
# " " : "lo",
# " " : "los",
"MÁNOS" : "mains",
"MAGÍS" : "mais",
"MAMẸLLAS" : "mamelles",
"MERCÁTÁNTS" : "marchaanz",
"MERCÁTU" : ["marchié", "marchie"],
"MERCÁTOS" : ["marchiés", "marchies"],
"MARÍA" : "marie",
"MEMBROS" : "menbres",
"MERÁBÍLYUNT" : [["meravilleront"], 'verbe_parfait'],
"MATRA" : "mere",
"MOLTU" : "molt",
# " " : "ne",
"NEGRỌR" : "nezor",
# " " : "nos",
# " " : "on",
# " " : "ont",
"PATÍẸNMẸNTE" : ["pacïenment", "pacienment"],
# " " : "per",
"PIETA" : "pidie",
# " " : "pié",
"PLẸNU" : "plein",
"PLẸNA" : "pleinna",
# " " : "por",
# " " : "qu",
# " " : "que",
# " " : "qui",
"RENAÍAS" : ["reneïes", "reneies"], #??
"REPRǪPYAS" : "reproches",
"REGÍ" : "roi",
# " " : "sa",
"SÁNCTA" : "sainte",
# " " : "se",
"SẸNE" : ["senz", "sents"],
# " " : "ses",
"SEPELÍRE" : "sevelir",
"SỌFFRĘT" : [["soffroit"], 'verbe_imparfait'],
# " " : "son",
"SỌBẸNDE" : "sovent",
"TANTỌST" : "tantost",
"TENDIT" : "tendit",
"TERRÁUTS" : ["terrauz", "terrauts"],
"TORNARUNT" : [["torneront"], 'verbe_imparfait'],
"TORQUOT" : "torzot",
"TRABÚCAT" : [["trabucha"], 'verbe_parfait'],
"TRACTA" : ["traitë", "traite"],
"TỌTTĪ" : "tuit",
"UNU" : "un",
"UNOS" : "uns",
"VENDĘT" : [["vendoit"], 'verbe_imparfait'],
"VẸNDCA" : [["venga"], 'verbe_parfait'],
"VẸNDCÁNCYA" : "vengance",
"VENÚ" : [["venu"], 'verbe_parfait'],
"VEÚ" : [["veü", 'veu'], 'verbe_parfait'],
"VIRGA" : "virgine",
# " " : "ço",
}
