print(EvolutionPhonetique.evolution_phonetique("HAT")) # ha
print(EvolutionPhonetique.evolution_phonetique("ACCAPTĘT")) # achatoit
print(EvolutionPhonetique.evolution_phonetique("AMLĘT")) # alloit
print(EvolutionPhonetique.evolution_phonetique("AMĘN")) # amen
print(EvolutionPhonetique.evolution_phonetique("APPRĘSSU")) # aprés
print(EvolutionPhonetique.evolution_phonetique("ADRĘTYOS")) # arieres
print(EvolutionPhonetique.evolution_phonetique("ADVERSU")) # avers
print(EvolutionPhonetique.evolution_phonetique("BONUS")) # bons
print(EvolutionPhonetique.evolution_phonetique("CAMBYARAS")) # changeres
print(EvolutionPhonetique.evolution_phonetique("CĘLU")) # ciel
print(EvolutionPhonetique.evolution_phonetique("COMMANDA")) # comanda
print(EvolutionPhonetique.evolution_phonetique("COMĘNTYA")) # comença
print(EvolutionPhonetique.evolution_phonetique("CORPUS")) # cors
print(EvolutionPhonetique.evolution_phonetique("CRESSÍST")) # cressist
print(EvolutionPhonetique.evolution_phonetique("CRISTU")) # crist
print(EvolutionPhonetique.evolution_phonetique("DE LEGÁLUS")) # delëauz
print(EvolutionPhonetique.evolution_phonetique("DĘU")) # deu
print(EvolutionPhonetique.evolution_phonetique("DĘOS")) # deus
print(EvolutionPhonetique.evolution_phonetique("DIT")) # dit
print(EvolutionPhonetique.evolution_phonetique("DOLANTS")) # dolenz
print(EvolutionPhonetique.evolution_phonetique("DỌLCA")) # douce
print(EvolutionPhonetique.evolution_phonetique("EN TORNU")) # entor
print(EvolutionPhonetique.evolution_phonetique("EN VERSU")) # envers
print(EvolutionPhonetique.evolution_phonetique("ERAT")) # ere
print(EvolutionPhonetique.evolution_phonetique("ERUNT")) # eront
print(EvolutionPhonetique.evolution_phonetique("EST")) # est
print(EvolutionPhonetique.evolution_phonetique("ESTĘT")) # estoit
print(EvolutionPhonetique.evolution_phonetique("FÁCĘT")) # faisoit
print(EvolutionPhonetique.evolution_phonetique("FÁCIT")) # fait
print(EvolutionPhonetique.evolution_phonetique("FẸDE")) # fei
print(EvolutionPhonetique.evolution_phonetique("FELỌNS")) # fellons
print(EvolutionPhonetique.evolution_phonetique("FẸNÍT")) # fenit
print(EvolutionPhonetique.evolution_phonetique("FORS")) # fors
print(EvolutionPhonetique.evolution_phonetique("WAÍDAN")) # gaaing
print(EvolutionPhonetique.evolution_phonetique("JẸCTA")) # gité
print(EvolutionPhonetique.evolution_phonetique("GRAVẸUNT")) # grevoient
print(EvolutionPhonetique.evolution_phonetique("ǪMO")) # hom
print(EvolutionPhonetique.evolution_phonetique("HONỌRÁRE")) # honorer
print(EvolutionPhonetique.evolution_phonetique("EXÍT")) # issi
print(EvolutionPhonetique.evolution_phonetique("JADÍES")) # jadis
print(EvolutionPhonetique.evolution_phonetique("GAUDYA")) # joi
print(EvolutionPhonetique.evolution_phonetique("JUDCAMẸNTE")) # jugement
print(EvolutionPhonetique.evolution_phonetique("JURA")) # jura
print(EvolutionPhonetique.evolution_phonetique("JURÁRE")) # jurer
print(EvolutionPhonetique.evolution_phonetique("JURẸT")) # juroit
print(EvolutionPhonetique.evolution_phonetique("LAYDẸAMẸNTS")) # laideiemenz
print(EvolutionPhonetique.evolution_phonetique("LAYDẸÁRE")) # laideier
print(EvolutionPhonetique.evolution_phonetique("LASSATU")) # laisé
print(EvolutionPhonetique.evolution_phonetique("LẸNGWA")) # lengue
print(EvolutionPhonetique.evolution_phonetique("LABRAS")) # levres
print(EvolutionPhonetique.evolution_phonetique("MÁNOS")) # mains
print(EvolutionPhonetique.evolution_phonetique("MAGÍS")) # mais
print(EvolutionPhonetique.evolution_phonetique("MAMẸLLAS")) # mamelles
print(EvolutionPhonetique.evolution_phonetique("MERCÁTÁNTS")) # marchaanz
print(EvolutionPhonetique.evolution_phonetique("MERCÁTU")) # marchié
print(EvolutionPhonetique.evolution_phonetique("MERCÁTOS")) # marchiés
print(EvolutionPhonetique.evolution_phonetique("MARÍA")) # marie
print(EvolutionPhonetique.evolution_phonetique("MEMBROS")) # menbres
print(EvolutionPhonetique.evolution_phonetique("MERÁBÍLYUNT")) # meravilleront
print(EvolutionPhonetique.evolution_phonetique("MATRA")) # mere
print(EvolutionPhonetique.evolution_phonetique("MOLTU")) # molt
print(EvolutionPhonetique.evolution_phonetique("NEGRỌR")) # nezor
print(EvolutionPhonetique.evolution_phonetique("PATÍẸNMẸNTE")) # pacïenment
print(EvolutionPhonetique.evolution_phonetique("PIETA")) # pidie
print(EvolutionPhonetique.evolution_phonetique("PLẸNU")) # plein
print(EvolutionPhonetique.evolution_phonetique("PLẸNA")) # pleinna
print(EvolutionPhonetique.evolution_phonetique("RENAÍAS")) # reneïes
print(EvolutionPhonetique.evolution_phonetique("REPRǪPYAS")) # reproches
print(EvolutionPhonetique.evolution_phonetique("REGÍ")) # roi
print(EvolutionPhonetique.evolution_phonetique("SÁNCTA")) # sainte
print(EvolutionPhonetique.evolution_phonetique("SẸNE")) # senz
print(EvolutionPhonetique.evolution_phonetique("SEPELÍRE")) # sevelir
print(EvolutionPhonetique.evolution_phonetique("SỌFFRĘT")) # soffroit
print(EvolutionPhonetique.evolution_phonetique("SỌBẸNDE")) # sovent
print(EvolutionPhonetique.evolution_phonetique("TANTỌST")) # tantost
print(EvolutionPhonetique.evolution_phonetique("TENDIT")) # tendit
print(EvolutionPhonetique.evolution_phonetique("TERRÁUTS")) # terrauz
print(EvolutionPhonetique.evolution_phonetique("TORNARUNT")) # torneront
print(EvolutionPhonetique.evolution_phonetique("TORQUOT")) # torzot
print(EvolutionPhonetique.evolution_phonetique("TRABÚCAT")) # trabucha
print(EvolutionPhonetique.evolution_phonetique("TRACTA")) # traitë
print(EvolutionPhonetique.evolution_phonetique("TỌTTĪ")) # tuit
print(EvolutionPhonetique.evolution_phonetique("UNU")) # un
print(EvolutionPhonetique.evolution_phonetique("UNOS")) # uns
print(EvolutionPhonetique.evolution_phonetique("VENDĘT")) # vendoit
print(EvolutionPhonetique.evolution_phonetique("VẸNDCA")) # venga
print(EvolutionPhonetique.evolution_phonetique("VẸNDCÁNCYA")) # vengance
print(EvolutionPhonetique.evolution_phonetique("VENÚ")) # venu
print(EvolutionPhonetique.evolution_phonetique("VEÚ")) # veü
print(EvolutionPhonetique.evolution_phonetique("VIRGA")) # virgine
